// Strings for the "browse" screens. Every key in `en` must exist in es, fr, ht and pt (the types enforce it).
// Placeholders like {n} are filled by t('key', { n: 3 }).
const en = {
  // Tabs header
  b_notifUnreadLabel: 'Notifications, {n} unread',
  // Community
  b_communitySignedOut: 'Ask for a hand at harvest, share equipment, offer seedlings, find a ride to market or a mentor. Members only.',
  b_everything: 'Everything',
  b_noPostsYet: 'Nothing posted here yet. Be the first.',
  b_boardRules: 'Posts close on their own after 45 days. Reply privately to arrange details; never share bank details on the board.',
  b_couldNotReply: 'Could not reply',
  b_notUpdated: 'Not updated',
  b_reportNotSent: 'Report not sent',
  b_reportSent: 'Report sent',
  b_reportSentBody: 'BFI moderators will review this post.',
  b_you: 'You',
  b_aMember: 'A member',
  b_memberFallback: 'Member',
  b_authorGrower: '{name}, grower',
  b_authorStaff: '{name}, BFI staff',
  b_onDate: 'On {date}',
  // Events
  b_rsvpNotSaved: 'RSVP not saved',
  b_reminderNotSaved: 'Reminder not saved',
  b_signupNotSaved: 'Sign-up not saved',
  b_noEvents: 'No upcoming events yet.',
  b_waitingApproval: 'Waiting for BFI approval',
  b_hostedBy: 'Hosted by {name}',
  b_tickets: 'Tickets',
  b_remindPush: 'Push',
  b_remindText: 'Text',
  b_spotsOpenOne: '{n} open',
  b_spotsOpenMany: '{n} open',
  b_eventsFooter: 'Farmers post their own events. BFI or a regional coordinator approves them before they go public.',
  b_evtFarmDay: 'Farm day',
  b_evtMarket: 'Market',
  b_evtWorkshop: 'Workshop',
  b_evtVolunteer: 'Volunteer',
  b_evtTownHall: 'Town hall',
  // Discover
  b_locationUnavailable: 'Location unavailable',
  b_waitingReview: 'Waiting for BFI review',
  b_updateFresh: 'Update what’s fresh',
  b_growerOne: '{n} grower',
  b_growerMany: '{n} growers',
  b_nearestFrom: 'Nearest first, from {place}',
  b_yourLocation: 'your location',
  b_verifiedNewest: 'Verified by BFI, newest first',
  // Messages
  b_chooseConversation: 'Choose a conversation to read it here.',
  b_chooseChannel: 'Choose a channel to read it here.',
  b_noMessagesYet: 'No messages yet',
  b_inquiryPreview: 'Inquiry: {product}, {amount}',
  b_noConversations: 'No conversations yet. Open a farm and send an inquiry to start one.',
  b_noChannels: 'No channels yet.',
  b_channelsIntro: 'One channel per BFI region, plus topic groups',
  b_conversation: 'Conversation',
  b_unread: 'Unread',
  b_channelsRules: 'Anyone signed in can read channels. Verified growers and BFI staff can post. Every message can be reported.',
  b_directRules: 'Buyers can message only farms that accept messages.',
  b_noAnnouncements: 'No announcements from BFI yet.',
  b_officialAccount: 'Official account',
  b_openLink: 'Open link',
  // Resources
  b_notSaved: 'Not saved',
  b_deadlinesEmpty: 'Save a program below to keep it here. When BFI adds a deadline, you get reminders 30, 7 and 1 day before.',
  b_noDeadline: 'No deadline set',
  b_closed: 'Closed',
  b_daysLeftOne: '{n} day · {date}',
  b_daysLeftMany: '{n} days · {date}',
  b_farmType: 'Farm type',
  b_stage: 'Stage',
  b_programsFitOne: '{n} program fits',
  b_programsFitMany: '{n} programs fit',
  b_noProgramsMatch: 'No programs match. Try “Any”.',
  b_resourcesFooter: 'Summaries are in plain language. Each program sets its own rules and deadlines, so check the official site before applying.',
  b_kindFrom: '{kind} from {org}',
  b_rtAny: 'Any',
  b_rtProduce: 'Produce',
  b_rtMeat: 'Meat',
  b_rtHoney: 'Honey',
  b_rtEggs: 'Eggs',
  b_rtSeafood: 'Seafood',
  b_rsStartingOut: 'Starting out',
  b_rsEstablished: 'Established',
  b_rkBfiProgram: 'BFI program',
  b_rkCostShare: 'Cost-share',
  b_rkLoan: 'Loan',
  b_rkLand: 'Land',
  b_rkGrant: 'Grant',
  b_rkSupport: 'Support',
  // Farm card and maps
  b_awaitingVerification: 'awaiting verification',
  b_mileAwayOne: '{n} mile away',
  b_milesAway: '{n} miles away',
  b_verifiedChip: 'Verified',
  b_awaitingReview: 'Awaiting review',
  b_milesShort: '{n} mi',
  b_harvestSlow: 'In harvest, may reply slowly',
  b_mapOfFarmsOne: 'Map of {n} farm',
  b_mapOfFarmsMany: 'Map of {n} farms',
  b_mapsUnavailable: 'Maps aren’t available here.',
  b_noCoords: 'None of these farms share map coordinates yet.',
  b_youAreHere: 'You are here',
  // Place picker
  b_placeNotFound: 'Place not found',
  b_nearPlace: 'Near {place}',
  b_change: 'Change',
  b_clear: 'Clear',
  b_townOrZip: 'Town and state, or ZIP code',
  b_go: 'Go',
  // BFI asks
  b_tapToAnswer: 'Tap to answer.',
  b_questionsOne: '{n} question.',
  b_questionsMany: '{n} questions.',
  b_quickQuestionsOne: '{n} quick question from BFI',
  b_quickQuestionsMany: '{n} quick questions from BFI',
  b_moreWaitingOne: '{n} more waiting',
  b_moreWaitingMany: '{n} more waiting',
  // Audiences
  b_audEveryone: 'Everyone',
  b_audGrowers: 'Growers',
  b_audNeighbors: 'Neighbors',
  b_whoGetsIt: 'Who gets it',
};
type Keys = Record<keyof typeof en, string>;

const es: Keys = {
  b_notifUnreadLabel: 'Notificaciones, {n} sin leer',
  b_communitySignedOut: 'Pide una mano en la cosecha, comparte equipo, ofrece plántulas, busca quién te lleve al mercado o un mentor. Solo para miembros.',
  b_everything: 'Todo',
  b_noPostsYet: 'Aún no hay publicaciones. ¡Haz la primera!',
  b_boardRules: 'Las publicaciones se cierran solas después de 45 días. Responde en privado para acordar los detalles; nunca compartas datos bancarios en el tablero.',
  b_couldNotReply: 'No se pudo responder',
  b_notUpdated: 'No se actualizó',
  b_reportNotSent: 'No se envió el reporte',
  b_reportSent: 'Reporte enviado',
  b_reportSentBody: 'Los moderadores de BFI revisarán esta publicación.',
  b_you: 'Tú',
  b_aMember: 'Un miembro',
  b_memberFallback: 'Miembro',
  b_authorGrower: '{name}, productor',
  b_authorStaff: '{name}, equipo de BFI',
  b_onDate: 'El {date}',
  b_rsvpNotSaved: 'No se guardó tu confirmación',
  b_reminderNotSaved: 'No se guardó el recordatorio',
  b_signupNotSaved: 'No se guardó la inscripción',
  b_noEvents: 'Aún no hay eventos próximos.',
  b_waitingApproval: 'Esperando aprobación de BFI',
  b_hostedBy: 'Organiza: {name}',
  b_tickets: 'Boletos',
  b_remindPush: 'Notificación',
  b_remindText: 'SMS',
  b_spotsOpenOne: '{n} lugar libre',
  b_spotsOpenMany: '{n} lugares libres',
  b_eventsFooter: 'Los agricultores publican sus propios eventos. BFI o un coordinador regional los aprueba antes de que se hagan públicos.',
  b_evtFarmDay: 'Día de granja',
  b_evtMarket: 'Mercado',
  b_evtWorkshop: 'Taller',
  b_evtVolunteer: 'Voluntariado',
  b_evtTownHall: 'Reunión comunitaria',
  b_locationUnavailable: 'Ubicación no disponible',
  b_waitingReview: 'Esperando revisión de BFI',
  b_updateFresh: 'Actualizar lo fresco',
  b_growerOne: '{n} productor',
  b_growerMany: '{n} productores',
  b_nearestFrom: 'Más cercanos primero, desde {place}',
  b_yourLocation: 'tu ubicación',
  b_verifiedNewest: 'Verificados por BFI, los más nuevos primero',
  b_chooseConversation: 'Elige una conversación para leerla aquí.',
  b_chooseChannel: 'Elige un canal para leerlo aquí.',
  b_noMessagesYet: 'Aún no hay mensajes',
  b_inquiryPreview: 'Consulta: {product}, {amount}',
  b_noConversations: 'Aún no hay conversaciones. Abre una granja y envía una consulta para empezar.',
  b_noChannels: 'Aún no hay canales.',
  b_channelsIntro: 'Un canal por región de BFI, más grupos temáticos',
  b_conversation: 'Conversación',
  b_unread: 'Sin leer',
  b_channelsRules: 'Cualquier persona con sesión iniciada puede leer los canales. Los productores verificados y el equipo de BFI pueden publicar. Todo mensaje se puede reportar.',
  b_directRules: 'Los compradores solo pueden escribir a granjas que aceptan mensajes.',
  b_noAnnouncements: 'Aún no hay anuncios de BFI.',
  b_officialAccount: 'Cuenta oficial',
  b_openLink: 'Abrir enlace',
  b_notSaved: 'No se guardó',
  b_deadlinesEmpty: 'Guarda un programa abajo para tenerlo aquí. Cuando BFI agregue una fecha límite, recibirás recordatorios 30, 7 y 1 día antes.',
  b_noDeadline: 'Sin fecha límite',
  b_closed: 'Cerrado',
  b_daysLeftOne: '{n} día · {date}',
  b_daysLeftMany: '{n} días · {date}',
  b_farmType: 'Tipo de granja',
  b_stage: 'Etapa',
  b_programsFitOne: '{n} programa para ti',
  b_programsFitMany: '{n} programas para ti',
  b_noProgramsMatch: 'Ningún programa coincide. Prueba “Cualquiera”.',
  b_resourcesFooter: 'Los resúmenes están en lenguaje sencillo. Cada programa fija sus propias reglas y fechas límite, así que revisa el sitio oficial antes de postularte.',
  b_kindFrom: '{kind} de {org}',
  b_rtAny: 'Cualquiera',
  b_rtProduce: 'Frutas y verduras',
  b_rtMeat: 'Carne',
  b_rtHoney: 'Miel',
  b_rtEggs: 'Huevos',
  b_rtSeafood: 'Mariscos',
  b_rsStartingOut: 'Comenzando',
  b_rsEstablished: 'Establecido',
  b_rkBfiProgram: 'Programa de BFI',
  b_rkCostShare: 'Costos compartidos',
  b_rkLoan: 'Préstamo',
  b_rkLand: 'Tierra',
  b_rkGrant: 'Subvención',
  b_rkSupport: 'Apoyo',
  b_awaitingVerification: 'pendiente de verificación',
  b_mileAwayOne: 'a {n} milla',
  b_milesAway: 'a {n} millas',
  b_verifiedChip: 'Verificada',
  b_awaitingReview: 'En revisión',
  b_milesShort: '{n} mi',
  b_harvestSlow: 'En cosecha, puede tardar en responder',
  b_mapOfFarmsOne: 'Mapa de {n} granja',
  b_mapOfFarmsMany: 'Mapa de {n} granjas',
  b_mapsUnavailable: 'Los mapas no están disponibles aquí.',
  b_noCoords: 'Ninguna de estas granjas comparte coordenadas todavía.',
  b_youAreHere: 'Estás aquí',
  b_placeNotFound: 'Lugar no encontrado',
  b_nearPlace: 'Cerca de {place}',
  b_change: 'Cambiar',
  b_clear: 'Borrar',
  b_townOrZip: 'Ciudad y estado, o código postal',
  b_go: 'Ir',
  b_tapToAnswer: 'Toca para responder.',
  b_questionsOne: '{n} pregunta.',
  b_questionsMany: '{n} preguntas.',
  b_quickQuestionsOne: '{n} pregunta rápida de BFI',
  b_quickQuestionsMany: '{n} preguntas rápidas de BFI',
  b_moreWaitingOne: '{n} más pendiente',
  b_moreWaitingMany: '{n} más pendientes',
  b_audEveryone: 'Todos',
  b_audGrowers: 'Productores',
  b_audNeighbors: 'Vecinos',
  b_whoGetsIt: 'Quién lo recibe',
};

const fr: Keys = {
  b_notifUnreadLabel: 'Notifications, {n} non lues',
  b_communitySignedOut: 'Demandez un coup de main pour la récolte, partagez du matériel, offrez des plants, trouvez un trajet vers le marché ou un mentor. Réservé aux membres.',
  b_everything: 'Tout',
  b_noPostsYet: 'Aucune publication pour l’instant. Lancez-vous !',
  b_boardRules: 'Les publications se ferment d’elles-mêmes après 45 jours. Répondez en privé pour régler les détails ; ne partagez jamais vos coordonnées bancaires sur le tableau.',
  b_couldNotReply: 'Impossible de répondre',
  b_notUpdated: 'Non mis à jour',
  b_reportNotSent: 'Signalement non envoyé',
  b_reportSent: 'Signalement envoyé',
  b_reportSentBody: 'Les modérateurs de BFI vont examiner cette publication.',
  b_you: 'Vous',
  b_aMember: 'Un membre',
  b_memberFallback: 'Membre',
  b_authorGrower: '{name}, producteur',
  b_authorStaff: '{name}, équipe BFI',
  b_onDate: 'Le {date}',
  b_rsvpNotSaved: 'Réponse non enregistrée',
  b_reminderNotSaved: 'Rappel non enregistré',
  b_signupNotSaved: 'Inscription non enregistrée',
  b_noEvents: 'Aucun événement à venir pour l’instant.',
  b_waitingApproval: 'En attente d’approbation par BFI',
  b_hostedBy: 'Organisé par {name}',
  b_tickets: 'Billets',
  b_remindPush: 'Notification',
  b_remindText: 'SMS',
  b_spotsOpenOne: '{n} place libre',
  b_spotsOpenMany: '{n} places libres',
  b_eventsFooter: 'Les agriculteurs publient leurs propres événements. BFI ou un coordinateur régional les approuve avant leur publication.',
  b_evtFarmDay: 'Journée à la ferme',
  b_evtMarket: 'Marché',
  b_evtWorkshop: 'Atelier',
  b_evtVolunteer: 'Bénévolat',
  b_evtTownHall: 'Réunion publique',
  b_locationUnavailable: 'Position indisponible',
  b_waitingReview: 'En attente de vérification par BFI',
  b_updateFresh: 'Mettre à jour les produits frais',
  b_growerOne: '{n} producteur',
  b_growerMany: '{n} producteurs',
  b_nearestFrom: 'Les plus proches d’abord, depuis {place}',
  b_yourLocation: 'votre position',
  b_verifiedNewest: 'Vérifiés par BFI, les plus récents d’abord',
  b_chooseConversation: 'Choisissez une conversation pour la lire ici.',
  b_chooseChannel: 'Choisissez un canal pour le lire ici.',
  b_noMessagesYet: 'Pas encore de messages',
  b_inquiryPreview: 'Demande : {product}, {amount}',
  b_noConversations: 'Aucune conversation pour l’instant. Ouvrez une ferme et envoyez une demande pour commencer.',
  b_noChannels: 'Aucun canal pour l’instant.',
  b_channelsIntro: 'Un canal par région BFI, plus des groupes thématiques',
  b_conversation: 'Conversation',
  b_unread: 'Non lu',
  b_channelsRules: 'Toute personne connectée peut lire les canaux. Les producteurs vérifiés et l’équipe BFI peuvent publier. Chaque message peut être signalé.',
  b_directRules: 'Les acheteurs ne peuvent écrire qu’aux fermes qui acceptent les messages.',
  b_noAnnouncements: 'Aucune annonce de BFI pour l’instant.',
  b_officialAccount: 'Compte officiel',
  b_openLink: 'Ouvrir le lien',
  b_notSaved: 'Non enregistré',
  b_deadlinesEmpty: 'Enregistrez un programme ci-dessous pour le garder ici. Quand BFI ajoute une date limite, vous recevez des rappels 30, 7 et 1 jour avant.',
  b_noDeadline: 'Pas de date limite',
  b_closed: 'Clôturé',
  b_daysLeftOne: '{n} jour · {date}',
  b_daysLeftMany: '{n} jours · {date}',
  b_farmType: 'Type de ferme',
  b_stage: 'Étape',
  b_programsFitOne: '{n} programme adapté',
  b_programsFitMany: '{n} programmes adaptés',
  b_noProgramsMatch: 'Aucun programme ne correspond. Essayez « Tous ».',
  b_resourcesFooter: 'Les résumés sont en langage simple. Chaque programme fixe ses propres règles et dates limites : vérifiez le site officiel avant de postuler.',
  b_kindFrom: '{kind} · {org}',
  b_rtAny: 'Tous',
  b_rtProduce: 'Fruits et légumes',
  b_rtMeat: 'Viande',
  b_rtHoney: 'Miel',
  b_rtEggs: 'Œufs',
  b_rtSeafood: 'Fruits de mer',
  b_rsStartingOut: 'Débutant',
  b_rsEstablished: 'Établi',
  b_rkBfiProgram: 'Programme BFI',
  b_rkCostShare: 'Partage des coûts',
  b_rkLoan: 'Prêt',
  b_rkLand: 'Terres',
  b_rkGrant: 'Subvention',
  b_rkSupport: 'Soutien',
  b_awaitingVerification: 'en attente de vérification',
  b_mileAwayOne: 'à {n} mile',
  b_milesAway: 'à {n} miles',
  b_verifiedChip: 'Vérifiée',
  b_awaitingReview: 'En cours d’examen',
  b_milesShort: '{n} mi',
  b_harvestSlow: 'En pleine récolte, réponse parfois lente',
  b_mapOfFarmsOne: 'Carte de {n} ferme',
  b_mapOfFarmsMany: 'Carte de {n} fermes',
  b_mapsUnavailable: 'Les cartes ne sont pas disponibles ici.',
  b_noCoords: 'Aucune de ces fermes ne partage encore ses coordonnées.',
  b_youAreHere: 'Vous êtes ici',
  b_placeNotFound: 'Lieu introuvable',
  b_nearPlace: 'Près de {place}',
  b_change: 'Modifier',
  b_clear: 'Effacer',
  b_townOrZip: 'Ville et État, ou code postal',
  b_go: 'OK',
  b_tapToAnswer: 'Touchez pour répondre.',
  b_questionsOne: '{n} question.',
  b_questionsMany: '{n} questions.',
  b_quickQuestionsOne: '{n} question rapide de BFI',
  b_quickQuestionsMany: '{n} questions rapides de BFI',
  b_moreWaitingOne: '{n} autre en attente',
  b_moreWaitingMany: '{n} autres en attente',
  b_audEveryone: 'Tout le monde',
  b_audGrowers: 'Producteurs',
  b_audNeighbors: 'Voisins',
  b_whoGetsIt: 'Destinataires',
};

const ht: Keys = {
  b_notifUnreadLabel: 'Notifikasyon, {n} pa li',
  b_communitySignedOut: 'Mande yon kout men pou rekòt, pataje ekipman, ofri ti plant, jwenn yon woulib pou al nan mache oswa yon mantò. Se pou manm sèlman.',
  b_everything: 'Tout',
  b_noPostsYet: 'Poko gen anyen la a. Se ou ki ka premye.',
  b_boardRules: 'Pòs yo fèmen pou kont yo apre 45 jou. Reponn an prive pou regle detay yo; pa janm pataje enfòmasyon bank ou sou tablo a.',
  b_couldNotReply: 'Nou pa t ka reponn',
  b_notUpdated: 'Li pa t mete ajou',
  b_reportNotSent: 'Rapò a pa t ale',
  b_reportSent: 'Rapò a ale',
  b_reportSentBody: 'Moderatè BFI yo pral egzamine pòs sa a.',
  b_you: 'Ou',
  b_aMember: 'Yon manm',
  b_memberFallback: 'Manm',
  b_authorGrower: '{name}, kiltivatè',
  b_authorStaff: '{name}, ekip BFI',
  b_onDate: 'Jou {date}',
  b_rsvpNotSaved: 'Repons ou pa t anrejistre',
  b_reminderNotSaved: 'Rapèl la pa t anrejistre',
  b_signupNotSaved: 'Enskripsyon an pa t anrejistre',
  b_noEvents: 'Poko gen evènman ki pral vini.',
  b_waitingApproval: 'N ap tann BFI apwouve l',
  b_hostedBy: 'Òganizatè: {name}',
  b_tickets: 'Tikè',
  b_remindPush: 'Notifikasyon',
  b_remindText: 'Tèks',
  b_spotsOpenOne: '{n} plas lib',
  b_spotsOpenMany: '{n} plas lib',
  b_eventsFooter: 'Kiltivatè yo poste pwòp evènman pa yo. BFI oswa yon kowòdonatè rejyonal apwouve yo anvan tout moun ka wè yo.',
  b_evtFarmDay: 'Jounen fèm',
  b_evtMarket: 'Mache',
  b_evtWorkshop: 'Atelye',
  b_evtVolunteer: 'Volontè',
  b_evtTownHall: 'Reyinyon kominotè',
  b_locationUnavailable: 'Pozisyon pa disponib',
  b_waitingReview: 'N ap tann BFI revize l',
  b_updateFresh: 'Mete sa ki fre ajou',
  b_growerOne: '{n} kiltivatè',
  b_growerMany: '{n} kiltivatè',
  b_nearestFrom: 'Pi pre yo an premye, apati {place}',
  b_yourLocation: 'kote ou ye a',
  b_verifiedNewest: 'BFI verifye yo, sa ki pi nouvo an premye',
  b_chooseConversation: 'Chwazi yon konvèsasyon pou li l la a.',
  b_chooseChannel: 'Chwazi yon kanal pou li l la a.',
  b_noMessagesYet: 'Poko gen mesaj',
  b_inquiryPreview: 'Demann: {product}, {amount}',
  b_noConversations: 'Poko gen konvèsasyon. Louvri yon fèm epi voye yon demann pou kòmanse.',
  b_noChannels: 'Poko gen kanal.',
  b_channelsIntro: 'Yon kanal pou chak rejyon BFI, plis gwoup sou kèk sijè',
  b_conversation: 'Konvèsasyon',
  b_unread: 'Pa li',
  b_channelsRules: 'Tout moun ki konekte ka li kanal yo. Kiltivatè ki verifye ak ekip BFI ka poste. Ou ka rapòte nenpòt mesaj.',
  b_directRules: 'Achtè yo ka voye mesaj sèlman bay fèm ki aksepte mesaj.',
  b_noAnnouncements: 'BFI poko fè okenn anons.',
  b_officialAccount: 'Kont ofisyèl',
  b_openLink: 'Louvri lyen an',
  b_notSaved: 'Pa t anrejistre',
  b_deadlinesEmpty: 'Anrejistre yon pwogram anba a pou kenbe l la a. Lè BFI mete yon dat limit, w ap resevwa rapèl 30, 7 ak 1 jou anvan.',
  b_noDeadline: 'Pa gen dat limit',
  b_closed: 'Fèmen',
  b_daysLeftOne: '{n} jou · {date}',
  b_daysLeftMany: '{n} jou · {date}',
  b_farmType: 'Kalite fèm',
  b_stage: 'Etap',
  b_programsFitOne: '{n} pwogram ki bon pou ou',
  b_programsFitMany: '{n} pwogram ki bon pou ou',
  b_noProgramsMatch: 'Pa gen pwogram ki koresponn. Eseye “Nenpòt”.',
  b_resourcesFooter: 'Rezime yo ekri nan langaj senp. Chak pwogram gen pwòp règ ak dat limit pa l, kidonk tcheke sit ofisyèl la anvan ou aplike.',
  b_kindFrom: '{kind} · {org}',
  b_rtAny: 'Nenpòt',
  b_rtProduce: 'Legim ak fwi',
  b_rtMeat: 'Vyann',
  b_rtHoney: 'Siwo myèl',
  b_rtEggs: 'Ze',
  b_rtSeafood: 'Fwi demè',
  b_rsStartingOut: 'K ap kòmanse',
  b_rsEstablished: 'Byen etabli',
  b_rkBfiProgram: 'Pwogram BFI',
  b_rkCostShare: 'Pataj frè',
  b_rkLoan: 'Prè',
  b_rkLand: 'Tè',
  b_rkGrant: 'Sibvansyon',
  b_rkSupport: 'Sipò',
  b_awaitingVerification: 'ap tann verifikasyon',
  b_mileAwayOne: '{n} mil de la',
  b_milesAway: '{n} mil de la',
  b_verifiedChip: 'Verifye',
  b_awaitingReview: 'Ap tann revizyon',
  b_milesShort: '{n} mi',
  b_harvestSlow: 'Nan rekòt, li ka pran tan pou reponn',
  b_mapOfFarmsOne: 'Kat {n} fèm',
  b_mapOfFarmsMany: 'Kat {n} fèm',
  b_mapsUnavailable: 'Kat yo pa disponib isit la.',
  b_noCoords: 'Okenn nan fèm sa yo poko pataje kote yo ye sou kat la.',
  b_youAreHere: 'Ou isit la',
  b_placeNotFound: 'Nou pa jwenn kote sa a',
  b_nearPlace: 'Toupre {place}',
  b_change: 'Chanje',
  b_clear: 'Efase',
  b_townOrZip: 'Vil ak eta, oswa kòd postal',
  b_go: 'Ale',
  b_tapToAnswer: 'Tape pou reponn.',
  b_questionsOne: '{n} kesyon.',
  b_questionsMany: '{n} kesyon.',
  b_quickQuestionsOne: '{n} ti kesyon BFI',
  b_quickQuestionsMany: '{n} ti kesyon BFI',
  b_moreWaitingOne: '{n} lòt k ap tann',
  b_moreWaitingMany: '{n} lòt k ap tann',
  b_audEveryone: 'Tout moun',
  b_audGrowers: 'Kiltivatè',
  b_audNeighbors: 'Vwazen',
  b_whoGetsIt: 'Kiyès ki resevwa l',
};

const pt: Keys = {
  b_notifUnreadLabel: 'Notificações, {n} não lidas',
  b_communitySignedOut: 'Peça uma mão na colheita, compartilhe equipamentos, ofereça mudas, encontre carona para a feira ou um mentor. Só para membros.',
  b_everything: 'Tudo',
  b_noPostsYet: 'Nada publicado ainda. Seja o primeiro!',
  b_boardRules: 'As publicações se encerram sozinhas após 45 dias. Responda em particular para combinar os detalhes; nunca compartilhe dados bancários no mural.',
  b_couldNotReply: 'Não foi possível responder',
  b_notUpdated: 'Não atualizado',
  b_reportNotSent: 'Denúncia não enviada',
  b_reportSent: 'Denúncia enviada',
  b_reportSentBody: 'Os moderadores da BFI vão analisar esta publicação.',
  b_you: 'Você',
  b_aMember: 'Um membro',
  b_memberFallback: 'Membro',
  b_authorGrower: '{name}, produtor',
  b_authorStaff: '{name}, equipe da BFI',
  b_onDate: 'Em {date}',
  b_rsvpNotSaved: 'Confirmação não salva',
  b_reminderNotSaved: 'Lembrete não salvo',
  b_signupNotSaved: 'Inscrição não salva',
  b_noEvents: 'Ainda não há eventos próximos.',
  b_waitingApproval: 'Aguardando aprovação da BFI',
  b_hostedBy: 'Organizado por {name}',
  b_tickets: 'Ingressos',
  b_remindPush: 'Notificação',
  b_remindText: 'SMS',
  b_spotsOpenOne: '{n} vaga',
  b_spotsOpenMany: '{n} vagas',
  b_eventsFooter: 'Os agricultores publicam seus próprios eventos. A BFI ou um coordenador regional aprova antes de ficarem públicos.',
  b_evtFarmDay: 'Dia na fazenda',
  b_evtMarket: 'Feira',
  b_evtWorkshop: 'Oficina',
  b_evtVolunteer: 'Voluntariado',
  b_evtTownHall: 'Reunião comunitária',
  b_locationUnavailable: 'Localização indisponível',
  b_waitingReview: 'Aguardando análise da BFI',
  b_updateFresh: 'Atualizar o que está fresco',
  b_growerOne: '{n} produtor',
  b_growerMany: '{n} produtores',
  b_nearestFrom: 'Mais próximos primeiro, a partir de {place}',
  b_yourLocation: 'sua localização',
  b_verifiedNewest: 'Verificados pela BFI, mais recentes primeiro',
  b_chooseConversation: 'Escolha uma conversa para ler aqui.',
  b_chooseChannel: 'Escolha um canal para ler aqui.',
  b_noMessagesYet: 'Nenhuma mensagem ainda',
  b_inquiryPreview: 'Pedido: {product}, {amount}',
  b_noConversations: 'Nenhuma conversa ainda. Abra uma fazenda e envie um pedido para começar.',
  b_noChannels: 'Nenhum canal ainda.',
  b_channelsIntro: 'Um canal por região da BFI, além de grupos temáticos',
  b_conversation: 'Conversa',
  b_unread: 'Não lida',
  b_channelsRules: 'Qualquer pessoa conectada pode ler os canais. Produtores verificados e a equipe da BFI podem publicar. Toda mensagem pode ser denunciada.',
  b_directRules: 'Compradores só podem enviar mensagens para fazendas que aceitam mensagens.',
  b_noAnnouncements: 'Nenhum anúncio da BFI ainda.',
  b_officialAccount: 'Conta oficial',
  b_openLink: 'Abrir link',
  b_notSaved: 'Não salvo',
  b_deadlinesEmpty: 'Salve um programa abaixo para mantê-lo aqui. Quando a BFI adicionar um prazo, você recebe lembretes 30, 7 e 1 dia antes.',
  b_noDeadline: 'Sem prazo',
  b_closed: 'Encerrado',
  b_daysLeftOne: '{n} dia · {date}',
  b_daysLeftMany: '{n} dias · {date}',
  b_farmType: 'Tipo de fazenda',
  b_stage: 'Fase',
  b_programsFitOne: '{n} programa para você',
  b_programsFitMany: '{n} programas para você',
  b_noProgramsMatch: 'Nenhum programa corresponde. Tente “Qualquer”.',
  b_resourcesFooter: 'Os resumos estão em linguagem simples. Cada programa define suas próprias regras e prazos, então confira o site oficial antes de se inscrever.',
  b_kindFrom: '{kind} · {org}',
  b_rtAny: 'Qualquer',
  b_rtProduce: 'Hortifrúti',
  b_rtMeat: 'Carne',
  b_rtHoney: 'Mel',
  b_rtEggs: 'Ovos',
  b_rtSeafood: 'Frutos do mar',
  b_rsStartingOut: 'Começando',
  b_rsEstablished: 'Estabelecido',
  b_rkBfiProgram: 'Programa da BFI',
  b_rkCostShare: 'Custo compartilhado',
  b_rkLoan: 'Empréstimo',
  b_rkLand: 'Terra',
  b_rkGrant: 'Subsídio',
  b_rkSupport: 'Apoio',
  b_awaitingVerification: 'aguardando verificação',
  b_mileAwayOne: 'a {n} milha',
  b_milesAway: 'a {n} milhas',
  b_verifiedChip: 'Verificada',
  b_awaitingReview: 'Em análise',
  b_milesShort: '{n} mi',
  b_harvestSlow: 'Em colheita, pode demorar a responder',
  b_mapOfFarmsOne: 'Mapa de {n} fazenda',
  b_mapOfFarmsMany: 'Mapa de {n} fazendas',
  b_mapsUnavailable: 'Os mapas não estão disponíveis aqui.',
  b_noCoords: 'Nenhuma destas fazendas compartilha coordenadas ainda.',
  b_youAreHere: 'Você está aqui',
  b_placeNotFound: 'Local não encontrado',
  b_nearPlace: 'Perto de {place}',
  b_change: 'Alterar',
  b_clear: 'Limpar',
  b_townOrZip: 'Cidade e estado, ou código postal',
  b_go: 'Ir',
  b_tapToAnswer: 'Toque para responder.',
  b_questionsOne: '{n} pergunta.',
  b_questionsMany: '{n} perguntas.',
  b_quickQuestionsOne: '{n} pergunta rápida da BFI',
  b_quickQuestionsMany: '{n} perguntas rápidas da BFI',
  b_moreWaitingOne: 'mais {n} aguardando',
  b_moreWaitingMany: 'mais {n} aguardando',
  b_audEveryone: 'Todos',
  b_audGrowers: 'Produtores',
  b_audNeighbors: 'Vizinhos',
  b_whoGetsIt: 'Quem recebe',
};

export default { en, es, fr, ht, pt };
