// Strings for the "member" screens. Every key in `en` must exist in es, fr, ht and pt (the types enforce it).
// Placeholders like {n} are filled by t('key', { n: 3 }).
const en = {
  m_errorTitle: 'Something went wrong on this screen',
  m_errorHint: 'Try again, or go back to Discover.',
  m_back: 'Back',
  m_backTo: 'Back to {label}',
  m_copied: 'Copied',
  m_quotedOnBfi: '{name} · quoted on BFI’s home page',
  m_bfiWorksToward: 'What BFI works toward',
  m_howItStarted: 'How it started',
  m_programs: 'Programs',
  m_partners: 'Partners',
  m_foundedBy: 'Founded by',
  m_contact: 'Contact',
  m_copy: 'Copy',
  m_copyItem: 'Copy {label}',
  m_donate: 'Donate',
  m_shop: 'Shop',
  m_visitWebsite: 'Visit the website',
  m_contentFrom: 'Content from blackfarmersindex.com, checked Oct 4, 2026.',
  m_choosePlaceFirst: 'Choose a place first',
  m_choosePlaceHint: 'Use your location or enter a town so we know what “near” means.',
  m_alertNotSaved: 'Alert not saved',
  m_notRemoved: 'Not removed',
  m_alertsIntro: 'We’ll tell you when a farm near you marks something fresh. Your location is saved only with the alert, and only you can see it.',
  m_newAlert: 'New alert',
  m_lookingFor: 'What are you looking for?',
  m_alertPlaceholder: 'Honey, okra, pastured eggs…',
  m_within: 'Within',
  m_nMiles: '{n} miles',
  m_saveAlert: 'Save alert',
  m_noAlerts: 'No alerts yet.',
  m_withinMilesOf: 'Within {n} miles of {place}',
  m_yourSavedLocation: 'your saved location',
  m_remove: 'Remove',
  m_locExact: '{city}, {state}. Address shared by the farm.',
  m_locPickup: 'Pickup at {place}. Farm address stays private.',
  m_locCity: '{city}, {state}. Exact address shared after an order.',
  m_couldNotUpdate: 'Could not update',
  m_messageNotStarted: 'Message not started',
  m_reportNotSent: 'Report not sent',
  m_reportSent: 'Report sent',
  m_reviewListing: 'BFI moderators will review this listing.',
  m_awaitingVerification: 'Awaiting verification',
  m_onIndexSince: 'On the Index since {year}.',
  m_onIndexSinceVerified: 'On the Index since {year}, verified by BFI {date}.',
  m_nothingThisWeek: 'Nothing posted this week. Follow the farm to hear when something comes in.',
  m_orderOnFarmSite: 'On the farm’s own site. Orders and payment go straight to the farm.',
  m_messageTheFarm: 'Message the farm',
  m_langsRepliesSms: '{langs}. Replies by text message.',
  m_website: 'Website',
  m_farmNotJoinedNote: 'This farm is listed on the Index but hasn’t joined the app yet, so it can’t receive messages here.',
  m_editMyFarm: 'Edit my farm',
  m_inquiryNotSent: 'Inquiry not sent',
  m_toFarm: 'To {name}',
  m_whenYmd: 'When (year-month-day)',
  m_dateHintToday: 'Use a real date from today on, like {today}.',
  m_notUpdated: 'Not updated',
  m_notAdded: 'Not added',
  m_notSaved: 'Not saved',
  m_waitingReview: 'Waiting for BFI review',
  m_reviewsNewListing: 'BFI reviews every new listing. You can set up your products now; your farm goes live once it’s approved.',
  m_freshTapToggle: 'What’s fresh this week · tap to turn on or off',
  m_addProduct: 'Add a product',
  m_addProductPlaceholder: 'For example: Turnip greens',
  m_add: 'Add',
  m_followersNotified: 'Followers get a notification when you mark something fresh.',
  m_harvestModeHint: "Shows buyers you're in harvest and may reply slowly.",
  m_acceptMessages: 'Accept messages from buyers',
  m_replyByText: 'I reply by text message',
  m_replyByTextHint: 'Messages reach you by text when you’ve turned on text messages in Settings. Reply to the text to answer, starting with the code in it (like #K7P). For an inquiry, add YES, PART or NO after the code.',
  m_viewPublicProfile: 'View my public profile',
  m_orderLinkIntro: 'Have an online store, CSA sign-up or market page? Add it and buyers see an “{button}” button on your profile. Orders and payment go straight to you.',
  m_link: 'Link',
  m_notWebAddress: 'That doesn’t look like a web address yet.',
  m_buttonTextOptional: 'Button text (optional)',
  m_buttonTextPlaceholder: 'For example: Join our CSA',
  m_listingNotSent: 'Listing not sent',
  m_sentToBfi: 'Sent to BFI',
  m_listingSentBody: 'BFI will review your listing. You can add your products while you wait.',
  m_listingFreeVerified: 'Listing on the Index is free. BFI reviews every farm before it goes live and marks it verified.',
  m_farmName: 'Farm name',
  m_cityOrTown: 'City or town',
  m_state: 'State',
  m_bfiRegion: 'BFI region',
  m_whatGrow: 'What do you grow or raise?',
  m_storyOptional: 'Your story (optional)',
  m_storyPlaceholder: 'A few sentences about your farm',
  m_howBuyLines: 'How people can buy (one per line)',
  m_howBuyPlaceholder: 'Farm stand, Saturdays\nCSA boxes',
  m_howMuchLocation: 'How much location to show',
  m_cityOnly: 'City only',
  m_aPickupPoint: 'A pickup point',
  m_exactAddress: 'Exact address',
  m_pickupPoint: 'Pickup point',
  m_pickupPlaceholder: 'For example: Saturday market, Main St',
  m_addressNeverShown: 'Your street address is never shown unless you choose “{option}”.',
  m_sendForReview: 'Send to BFI for review',
  m_profileViews: 'Profile views',
  m_followers: 'Followers',
  m_inquiries: 'Inquiries',
  m_answerOpenInquiry: 'Answer 1 open inquiry',
  m_answerOpenInquiries: 'Answer {n} open inquiries',
  m_photosOff: 'Photos are off',
  m_allowPhotoAccess: 'Allow photo access for The Index in your phone settings.',
  m_photoNotAdded: 'Photo not added',
  m_tryAgainDot: 'Try again.',
  m_makeFirst: 'Make first',
  m_coverPhoto: 'Cover photo',
  m_removePhoto: 'Remove photo: {alt}',
  m_selectedPhoto: 'Selected photo',
  m_describePhoto: 'Describe the photo',
  m_describePhotoHint: "Read aloud for people who can't see it. For example: Rows of collards at sunrise.",
  m_photoConsent: 'I took this photo or have permission, and BFI may show it in the app',
  m_addPhotoBtn: 'Add photo',
  m_photosGetVisits: 'Farms with photos get more visits. Your first photo is the cover on your listing.',
  m_kindNeed: 'Need help',
  m_kindNeedHint: 'Harvest hands, a ride to market, advice',
  m_kindOffer: 'Offering',
  m_kindOfferHint: 'Seedlings, surplus produce, a skill',
  m_kindEquipment: 'Equipment',
  m_kindEquipmentHint: 'Tools, tractors or cold storage to lend or share',
  m_kindRide: 'Rides and hauling',
  m_kindRideHint: 'Carpools to events, shared trucking',
  m_kindBulk: 'Buying together',
  m_kindBulkHint: 'Pool orders for seed, feed or packaging',
  m_kindMentor: 'Mentoring',
  m_kindMentorHint: 'Offer or ask for guidance from another grower',
  m_useRealDate: 'Use a real date, like 2026-10-24.',
  m_pickTodayOrLater: 'Pick today or a later date.',
  m_notPosted: 'Not posted',
  m_whatKindOfPost: 'What kind of post?',
  m_headline: 'Headline',
  m_headlinePlaceholder: 'Need 3 people for sweet potato harvest',
  m_details: 'Details',
  m_detailsPlaceholder: 'What, when, and anything people should bring or know',
  m_whereOptional: 'Where (optional)',
  m_dateOptional: 'Date (optional)',
  m_post: 'Post',
  m_displayNameShows: 'Your display name shows on the post. People reply to you privately in Messages.',
  m_evFarmDay: 'Farm day',
  m_evMarket: 'Market',
  m_evWorkshop: 'Workshop',
  m_evVolunteer: 'Volunteer',
  m_evTownHall: 'Town hall',
  m_pickFutureDateTime: 'Pick a date and time that hasn’t passed yet.',
  m_use24h: 'Use a 24-hour time, like 10:00 or 14:30.',
  m_eventNotSent: 'Event not sent',
  m_eventSentBody: 'Your event will appear for everyone once BFI approves it.',
  m_eventsApproved: 'BFI or a regional coordinator approves events before they go public.',
  m_eventName: 'Event name',
  m_eventNamePlaceholder: 'U-pick sweet potatoes',
  m_type: 'Type',
  m_dateYmd: 'Date (year-month-day)',
  m_startTime: 'Start time',
  m_where: 'Where',
  m_detailsOptional: 'Details (optional)',
  m_sendForApproval: 'Send for approval',
  m_textSizeHint: 'This works on top of your phone’s own text size setting.',
  m_translateHint: 'Messages and listings can be translated into your language with the Translate button.',
  m_member: 'Member',
  m_signedOut: 'Signed out',
  m_bfiStaff: 'BFI staff',
  m_pushOff: 'Phone notifications are off',
  m_codeNotSent: 'Code not sent',
  m_notConfirmed: 'Not confirmed',
  m_codeNoMatch: 'That code didn’t match',
  m_checkTextTryAgain: 'Check the text and try again.',
  m_pushWebHint: 'Available in the iPhone and Android apps.',
  m_turningOn: 'Turning on…',
  m_pushHint: 'Replies, fresh products, reminders and BFI news.',
  m_emailHint: 'Event reminders, deadlines and BFI announcements.',
  m_smsIntro: 'For members who prefer texts. Message rates may apply. Reply STOP to any text to opt out.',
  m_confirmNumberCode: 'Confirm your number. We’ll text a 6-digit code to {phone}.',
  m_addNumberFirst: 'Add your number first',
  m_inboxHint: 'Everything also appears in your notifications inbox, whichever channels you choose.',
  m_codeDidNotWork: 'That code did not work',
  m_checkEmailCode: 'Check the code in your email, or send a new one.',
  m_notConfigured: 'This build isn’t connected to a database yet. See the README to add the Supabase settings.',
  m_emailCodeIntro: 'We’ll email you a 6-digit code. No password needed.',
  m_yourName: 'Your name',
  m_yourNamePlaceholder: "How you'd like to appear to others",
  m_emailMeCode: 'Email me a code',
  m_enterCodeSentTo: 'Enter the code we sent to {email}.',
  m_sixDigitCode: '6-digit code',
  m_differentEmail: 'Use a different email',
  m_signInConsent: 'By signing in you agree that BFI may contact you about your account. Your email is never shown to other members.',
  m_messageNotSent: 'Message not sent',
  m_conversation: 'Conversation',
  m_viewFarmProfile: 'View farm profile',
  m_noMessages: 'No messages yet.',
  m_channelPostOnly: 'Only verified growers and BFI staff can post in channels.',
  m_readOnlyConversation: 'You can read this conversation but not reply.',
  m_you: 'You',
  m_replyReady: "Yes, it's ready. See you then!",
  m_replyPartial: 'I have part of that this week. Want me to hold what I have?',
  m_replyUnavailable: "Not this week, sorry. I'll message you when it's back.",
  m_replyNotSent: 'Reply not sent',
  m_reviewMessage: 'BFI moderators will review this message.',
  m_notHidden: 'Not hidden',
  m_yourInquiry: 'Your inquiry',
  m_inquiryFrom: 'Inquiry from {name}',
  m_farmerReady: 'Farmer says: ready',
  m_farmerPartial: 'Farmer says: partly available',
  m_farmerUnavailable: 'Farmer says: not this week',
  m_answerReady: "Yes, it's ready",
  m_answerPartial: 'I have part of it',
  m_answerUnavailable: 'Not this week',
  m_pinned: 'pinned',
  m_hiddenByMod: 'hidden by a moderator',
  m_transcriptComing: 'Transcript on its way…',
  m_hideMessageFrom: 'Hide message from {name}',
  m_hide: 'Hide',
  m_translationUnavailable: 'Translation isn’t available right now.',
  m_photoCredit: 'Photo: {credit}',
  m_micOff: 'Microphone is off',
  m_allowMic: 'Allow microphone access for The Index in your phone settings to send voice notes.',
  m_recordingNotStarted: 'Recording didn’t start',
  m_micBusy: 'Another app may be using the microphone. Try again in a moment.',
  m_tooShort: 'Too short',
  m_holdLonger: 'Hold on a little longer before you stop.',
  m_voiceNotSent: 'Voice note not sent',
  m_recordingOneSecond: 'Recording, 1 second',
  m_recordingSeconds: 'Recording, {n} seconds',
  m_recordingUnavailable: 'Recording unavailable',
  m_pauseVoice: 'Pause voice note',
  m_playVoice: 'Play voice note, {length}',
  m_loading: 'Loading',
};
type Keys = Record<keyof typeof en, string>;
const es: Keys = {
  m_errorTitle: 'Algo salió mal en esta pantalla',
  m_errorHint: 'Intenta de nuevo o vuelve a Descubrir.',
  m_back: 'Atrás',
  m_backTo: 'Volver a {label}',
  m_copied: 'Copiado',
  m_quotedOnBfi: '{name} · citado en la página principal de BFI',
  m_bfiWorksToward: 'Lo que busca BFI',
  m_howItStarted: 'Cómo empezó',
  m_programs: 'Programas',
  m_partners: 'Aliados',
  m_foundedBy: 'Fundado por',
  m_contact: 'Contacto',
  m_copy: 'Copiar',
  m_copyItem: 'Copiar {label}',
  m_donate: 'Donar',
  m_shop: 'Tienda',
  m_visitWebsite: 'Visitar el sitio web',
  m_contentFrom: 'Contenido de blackfarmersindex.com, revisado el 4 de oct. de 2026.',
  m_choosePlaceFirst: 'Primero elige un lugar',
  m_choosePlaceHint: 'Usa tu ubicación o escribe un pueblo para saber qué significa “cerca”.',
  m_alertNotSaved: 'No se guardó la alerta',
  m_notRemoved: 'No se quitó',
  m_alertsIntro: 'Te avisaremos cuando una granja cercana marque algo fresco. Tu ubicación solo se guarda con la alerta y solo tú puedes verla.',
  m_newAlert: 'Nueva alerta',
  m_lookingFor: '¿Qué estás buscando?',
  m_alertPlaceholder: 'Miel, okra, huevos de pastoreo…',
  m_within: 'Dentro de',
  m_nMiles: '{n} millas',
  m_saveAlert: 'Guardar alerta',
  m_noAlerts: 'Aún no hay alertas.',
  m_withinMilesOf: 'A menos de {n} millas de {place}',
  m_yourSavedLocation: 'tu ubicación guardada',
  m_remove: 'Quitar',
  m_locExact: '{city}, {state}. La granja comparte la dirección.',
  m_locPickup: 'Recogida en {place}. La dirección de la granja es privada.',
  m_locCity: '{city}, {state}. La dirección exacta se comparte después de un pedido.',
  m_couldNotUpdate: 'No se pudo actualizar',
  m_messageNotStarted: 'No se pudo iniciar el mensaje',
  m_reportNotSent: 'No se envió el reporte',
  m_reportSent: 'Reporte enviado',
  m_reviewListing: 'Los moderadores de BFI revisarán esta ficha.',
  m_awaitingVerification: 'Pendiente de verificación',
  m_onIndexSince: 'En el Index desde {year}.',
  m_onIndexSinceVerified: 'En el Index desde {year}, verificada por BFI el {date}.',
  m_nothingThisWeek: 'Nada publicado esta semana. Sigue a la granja para saber cuando llegue algo.',
  m_orderOnFarmSite: 'En el sitio de la granja. Los pedidos y pagos van directo a la granja.',
  m_messageTheFarm: 'Escríbele a la granja',
  m_langsRepliesSms: '{langs}. Responde por mensaje de texto.',
  m_website: 'Sitio web',
  m_farmNotJoinedNote: 'Esta granja está en el Index pero aún no se ha unido a la app, así que no puede recibir mensajes aquí.',
  m_editMyFarm: 'Editar mi granja',
  m_inquiryNotSent: 'No se envió la consulta',
  m_toFarm: 'Para {name}',
  m_whenYmd: 'Cuándo (año-mes-día)',
  m_dateHintToday: 'Usa una fecha real a partir de hoy, como {today}.',
  m_notUpdated: 'No se actualizó',
  m_notAdded: 'No se agregó',
  m_notSaved: 'No se guardó',
  m_waitingReview: 'Esperando revisión de BFI',
  m_reviewsNewListing: 'BFI revisa cada ficha nueva. Ya puedes agregar tus productos; tu granja se publicará cuando la aprueben.',
  m_freshTapToggle: 'Lo fresco de esta semana · toca para activar o desactivar',
  m_addProduct: 'Agregar un producto',
  m_addProductPlaceholder: 'Por ejemplo: hojas de nabo',
  m_add: 'Agregar',
  m_followersNotified: 'Tus seguidores reciben un aviso cuando marcas algo como fresco.',
  m_harvestModeHint: 'Les muestra a los compradores que estás en cosecha y podrías tardar en responder.',
  m_acceptMessages: 'Aceptar mensajes de compradores',
  m_replyByText: 'Respondo por mensaje de texto',
  m_replyByTextHint: 'Los mensajes te llegan por texto si activaste los mensajes de texto en Ajustes. Responde al texto empezando con el código que trae (como #K7P). Para una consulta, agrega YES, PART o NO después del código.',
  m_viewPublicProfile: 'Ver mi perfil público',
  m_orderLinkIntro: '¿Tienes una tienda en línea, inscripción a CSA o página de mercado? Agrégala y los compradores verán un botón “{button}” en tu perfil. Los pedidos y pagos van directo a ti.',
  m_link: 'Enlace',
  m_notWebAddress: 'Eso todavía no parece una dirección web.',
  m_buttonTextOptional: 'Texto del botón (opcional)',
  m_buttonTextPlaceholder: 'Por ejemplo: Únete a nuestra CSA',
  m_listingNotSent: 'No se envió la ficha',
  m_sentToBfi: 'Enviado a BFI',
  m_listingSentBody: 'BFI revisará tu ficha. Puedes agregar tus productos mientras esperas.',
  m_listingFreeVerified: 'Aparecer en el Index es gratis. BFI revisa cada granja antes de publicarla y la marca como verificada.',
  m_farmName: 'Nombre de la granja',
  m_cityOrTown: 'Ciudad o pueblo',
  m_state: 'Estado',
  m_bfiRegion: 'Región de BFI',
  m_whatGrow: '¿Qué cultivas o crías?',
  m_storyOptional: 'Tu historia (opcional)',
  m_storyPlaceholder: 'Unas frases sobre tu granja',
  m_howBuyLines: 'Cómo pueden comprar (una por línea)',
  m_howBuyPlaceholder: 'Puesto en la granja, sábados\nCajas CSA',
  m_howMuchLocation: 'Cuánto mostrar de tu ubicación',
  m_cityOnly: 'Solo la ciudad',
  m_aPickupPoint: 'Un punto de recogida',
  m_exactAddress: 'Dirección exacta',
  m_pickupPoint: 'Punto de recogida',
  m_pickupPlaceholder: 'Por ejemplo: mercado del sábado, Main St',
  m_addressNeverShown: 'Tu dirección nunca se muestra a menos que elijas “{option}”.',
  m_sendForReview: 'Enviar a BFI para revisión',
  m_profileViews: 'Visitas al perfil',
  m_followers: 'Seguidores',
  m_inquiries: 'Consultas',
  m_answerOpenInquiry: 'Responder 1 consulta pendiente',
  m_answerOpenInquiries: 'Responder {n} consultas pendientes',
  m_photosOff: 'Las fotos están desactivadas',
  m_allowPhotoAccess: 'Permite el acceso a fotos para The Index en los ajustes del teléfono.',
  m_photoNotAdded: 'No se agregó la foto',
  m_tryAgainDot: 'Intenta de nuevo.',
  m_makeFirst: 'Poner primero',
  m_coverPhoto: 'Foto de portada',
  m_removePhoto: 'Quitar foto: {alt}',
  m_selectedPhoto: 'Foto seleccionada',
  m_describePhoto: 'Describe la foto',
  m_describePhotoHint: 'Se lee en voz alta para quienes no pueden verla. Por ejemplo: hileras de berza al amanecer.',
  m_photoConsent: 'Tomé esta foto o tengo permiso, y BFI puede mostrarla en la app',
  m_addPhotoBtn: 'Agregar foto',
  m_photosGetVisits: 'Las granjas con fotos reciben más visitas. Tu primera foto es la portada de tu ficha.',
  m_kindNeed: 'Necesito ayuda',
  m_kindNeedHint: 'Manos para la cosecha, un aventón al mercado, consejos',
  m_kindOffer: 'Ofrezco',
  m_kindOfferHint: 'Plántulas, excedentes de cosecha, una habilidad',
  m_kindEquipment: 'Equipo',
  m_kindEquipmentHint: 'Herramientas, tractores o cámaras frías para prestar o compartir',
  m_kindRide: 'Viajes y transporte',
  m_kindRideHint: 'Viajes compartidos a eventos, transporte compartido',
  m_kindBulk: 'Compras en grupo',
  m_kindBulkHint: 'Junten pedidos de semilla, alimento o empaques',
  m_kindMentor: 'Mentoría',
  m_kindMentorHint: 'Ofrece o pide orientación a otro productor',
  m_useRealDate: 'Usa una fecha real, como 2026-10-24.',
  m_pickTodayOrLater: 'Elige hoy o una fecha posterior.',
  m_notPosted: 'No se publicó',
  m_whatKindOfPost: '¿Qué tipo de publicación?',
  m_headline: 'Título',
  m_headlinePlaceholder: 'Necesito 3 personas para cosechar camote',
  m_details: 'Detalles',
  m_detailsPlaceholder: 'Qué, cuándo y lo que la gente debe traer o saber',
  m_whereOptional: 'Dónde (opcional)',
  m_dateOptional: 'Fecha (opcional)',
  m_post: 'Publicar',
  m_displayNameShows: 'Tu nombre visible aparece en la publicación. Te responden en privado en Mensajes.',
  m_evFarmDay: 'Día de granja',
  m_evMarket: 'Mercado',
  m_evWorkshop: 'Taller',
  m_evVolunteer: 'Voluntariado',
  m_evTownHall: 'Asamblea comunitaria',
  m_pickFutureDateTime: 'Elige una fecha y hora que aún no hayan pasado.',
  m_use24h: 'Usa el formato de 24 horas, como 10:00 o 14:30.',
  m_eventNotSent: 'No se envió el evento',
  m_eventSentBody: 'Tu evento aparecerá para todos cuando BFI lo apruebe.',
  m_eventsApproved: 'BFI o un coordinador regional aprueba los eventos antes de publicarlos.',
  m_eventName: 'Nombre del evento',
  m_eventNamePlaceholder: 'Cosecha tu propio camote',
  m_type: 'Tipo',
  m_dateYmd: 'Fecha (año-mes-día)',
  m_startTime: 'Hora de inicio',
  m_where: 'Dónde',
  m_detailsOptional: 'Detalles (opcional)',
  m_sendForApproval: 'Enviar para aprobación',
  m_textSizeHint: 'Esto se suma al tamaño de texto que ya tiene tu teléfono.',
  m_translateHint: 'Los mensajes y las fichas se pueden traducir a tu idioma con el botón Traducir.',
  m_member: 'Miembro',
  m_signedOut: 'Sesión cerrada',
  m_bfiStaff: 'Equipo de BFI',
  m_pushOff: 'Las notificaciones están desactivadas',
  m_codeNotSent: 'No se envió el código',
  m_notConfirmed: 'No se confirmó',
  m_codeNoMatch: 'Ese código no coincide',
  m_checkTextTryAgain: 'Revisa el mensaje e intenta de nuevo.',
  m_pushWebHint: 'Disponible en las apps de iPhone y Android.',
  m_turningOn: 'Activando…',
  m_pushHint: 'Respuestas, productos frescos, recordatorios y noticias de BFI.',
  m_emailHint: 'Recordatorios de eventos, fechas límite y anuncios de BFI.',
  m_smsIntro: 'Para quienes prefieren mensajes de texto. Pueden aplicar tarifas de mensajes. Responde STOP a cualquier texto para darte de baja.',
  m_confirmNumberCode: 'Confirma tu número. Te enviaremos un código de 6 dígitos al {phone}.',
  m_addNumberFirst: 'Primero agrega tu número',
  m_inboxHint: 'Todo aparece también en tu bandeja de notificaciones, sin importar qué canales elijas.',
  m_codeDidNotWork: 'Ese código no funcionó',
  m_checkEmailCode: 'Revisa el código en tu correo o pide uno nuevo.',
  m_notConfigured: 'Esta versión aún no está conectada a una base de datos. Consulta el README para agregar la configuración de Supabase.',
  m_emailCodeIntro: 'Te enviaremos un código de 6 dígitos por correo. No necesitas contraseña.',
  m_yourName: 'Tu nombre',
  m_yourNamePlaceholder: 'Cómo quieres que te vean los demás',
  m_emailMeCode: 'Envíame un código',
  m_enterCodeSentTo: 'Escribe el código que enviamos a {email}.',
  m_sixDigitCode: 'Código de 6 dígitos',
  m_differentEmail: 'Usar otro correo',
  m_signInConsent: 'Al iniciar sesión aceptas que BFI te contacte sobre tu cuenta. Tu correo nunca se muestra a otros miembros.',
  m_messageNotSent: 'No se envió el mensaje',
  m_conversation: 'Conversación',
  m_viewFarmProfile: 'Ver perfil de la granja',
  m_noMessages: 'Aún no hay mensajes.',
  m_channelPostOnly: 'Solo productores verificados y el equipo de BFI pueden publicar en los canales.',
  m_readOnlyConversation: 'Puedes leer esta conversación, pero no responder.',
  m_you: 'Tú',
  m_replyReady: 'Sí, ya está listo. ¡Nos vemos!',
  m_replyPartial: 'Esta semana tengo una parte. ¿Quieres que te aparte lo que tengo?',
  m_replyUnavailable: 'Esta semana no, lo siento. Te escribo cuando vuelva a haber.',
  m_replyNotSent: 'No se envió la respuesta',
  m_reviewMessage: 'Los moderadores de BFI revisarán este mensaje.',
  m_notHidden: 'No se ocultó',
  m_yourInquiry: 'Tu consulta',
  m_inquiryFrom: 'Consulta de {name}',
  m_farmerReady: 'El productor dice: listo',
  m_farmerPartial: 'El productor dice: disponible en parte',
  m_farmerUnavailable: 'El productor dice: esta semana no',
  m_answerReady: 'Sí, está listo',
  m_answerPartial: 'Tengo una parte',
  m_answerUnavailable: 'Esta semana no',
  m_pinned: 'fijado',
  m_hiddenByMod: 'ocultado por un moderador',
  m_transcriptComing: 'Transcripción en camino…',
  m_hideMessageFrom: 'Ocultar mensaje de {name}',
  m_hide: 'Ocultar',
  m_translationUnavailable: 'La traducción no está disponible ahora.',
  m_photoCredit: 'Foto: {credit}',
  m_micOff: 'El micrófono está desactivado',
  m_allowMic: 'Permite el acceso al micrófono para The Index en los ajustes del teléfono para enviar notas de voz.',
  m_recordingNotStarted: 'No empezó la grabación',
  m_micBusy: 'Puede que otra app esté usando el micrófono. Intenta de nuevo en un momento.',
  m_tooShort: 'Muy corto',
  m_holdLonger: 'Espera un poco más antes de detener.',
  m_voiceNotSent: 'No se envió la nota de voz',
  m_recordingOneSecond: 'Grabando, 1 segundo',
  m_recordingSeconds: 'Grabando, {n} segundos',
  m_recordingUnavailable: 'Grabación no disponible',
  m_pauseVoice: 'Pausar nota de voz',
  m_playVoice: 'Reproducir nota de voz, {length}',
  m_loading: 'Cargando',
};
const fr: Keys = {
  m_errorTitle: 'Un problème est survenu sur cet écran',
  m_errorHint: 'Réessayez ou revenez à Découvrir.',
  m_back: 'Retour',
  m_backTo: 'Retour à {label}',
  m_copied: 'Copié',
  m_quotedOnBfi: '{name} · cité sur la page d’accueil de BFI',
  m_bfiWorksToward: 'Les objectifs de BFI',
  m_howItStarted: 'Les débuts',
  m_programs: 'Programmes',
  m_partners: 'Partenaires',
  m_foundedBy: 'Fondé par',
  m_contact: 'Contact',
  m_copy: 'Copier',
  m_copyItem: 'Copier {label}',
  m_donate: 'Faire un don',
  m_shop: 'Boutique',
  m_visitWebsite: 'Visiter le site web',
  m_contentFrom: 'Contenu de blackfarmersindex.com, vérifié le 4 oct. 2026.',
  m_choosePlaceFirst: 'Choisissez d’abord un lieu',
  m_choosePlaceHint: 'Utilisez votre position ou saisissez une ville pour que nous sachions ce que « près » veut dire.',
  m_alertNotSaved: 'Alerte non enregistrée',
  m_notRemoved: 'Non supprimé',
  m_alertsIntro: 'Nous vous préviendrons quand une ferme près de chez vous signale un produit frais. Votre position est enregistrée seulement avec l’alerte, et vous seul pouvez la voir.',
  m_newAlert: 'Nouvelle alerte',
  m_lookingFor: 'Que cherchez-vous ?',
  m_alertPlaceholder: 'Miel, gombo, œufs de plein air…',
  m_within: 'Dans un rayon de',
  m_nMiles: '{n} miles',
  m_saveAlert: 'Enregistrer l’alerte',
  m_noAlerts: 'Aucune alerte pour l’instant.',
  m_withinMilesOf: 'À moins de {n} miles de {place}',
  m_yourSavedLocation: 'votre position enregistrée',
  m_remove: 'Supprimer',
  m_locExact: '{city}, {state}. Adresse partagée par la ferme.',
  m_locPickup: 'Retrait à {place}. L’adresse de la ferme reste privée.',
  m_locCity: '{city}, {state}. Adresse exacte partagée après une commande.',
  m_couldNotUpdate: 'Mise à jour impossible',
  m_messageNotStarted: 'Message non commencé',
  m_reportNotSent: 'Signalement non envoyé',
  m_reportSent: 'Signalement envoyé',
  m_reviewListing: 'Les modérateurs de BFI examineront cette fiche.',
  m_awaitingVerification: 'En attente de vérification',
  m_onIndexSince: 'Sur l’Index depuis {year}.',
  m_onIndexSinceVerified: 'Sur l’Index depuis {year}, vérifiée par BFI le {date}.',
  m_nothingThisWeek: 'Rien de publié cette semaine. Suivez la ferme pour être prévenu des arrivages.',
  m_orderOnFarmSite: 'Sur le site de la ferme. Commandes et paiements vont directement à la ferme.',
  m_messageTheFarm: 'Écrivez à la ferme',
  m_langsRepliesSms: '{langs}. Répond par SMS.',
  m_website: 'Site web',
  m_farmNotJoinedNote: 'Cette ferme figure sur l’Index mais n’a pas encore rejoint l’appli, elle ne peut donc pas recevoir de messages ici.',
  m_editMyFarm: 'Modifier ma ferme',
  m_inquiryNotSent: 'Demande non envoyée',
  m_toFarm: 'À {name}',
  m_whenYmd: 'Quand (année-mois-jour)',
  m_dateHintToday: 'Indiquez une vraie date à partir d’aujourd’hui, comme {today}.',
  m_notUpdated: 'Non mis à jour',
  m_notAdded: 'Non ajouté',
  m_notSaved: 'Non enregistré',
  m_waitingReview: 'En attente de l’examen de BFI',
  m_reviewsNewListing: 'BFI examine chaque nouvelle fiche. Vous pouvez ajouter vos produits dès maintenant ; votre ferme sera publiée une fois approuvée.',
  m_freshTapToggle: 'Produits frais cette semaine · touchez pour activer ou désactiver',
  m_addProduct: 'Ajouter un produit',
  m_addProductPlaceholder: 'Par exemple : fanes de navet',
  m_add: 'Ajouter',
  m_followersNotified: 'Vos abonnés sont prévenus quand vous signalez un produit frais.',
  m_harvestModeHint: 'Indique aux acheteurs que vous êtes en récolte et pourriez répondre lentement.',
  m_acceptMessages: 'Accepter les messages des acheteurs',
  m_replyByText: 'Je réponds par SMS',
  m_replyByTextHint: 'Les messages vous arrivent par SMS si vous avez activé les SMS dans Réglages. Répondez au SMS en commençant par le code qu’il contient (comme #K7P). Pour une demande, ajoutez YES, PART ou NO après le code.',
  m_viewPublicProfile: 'Voir mon profil public',
  m_orderLinkIntro: 'Vous avez une boutique en ligne, une inscription AMAP ou une page de marché ? Ajoutez-la et les acheteurs verront un bouton « {button} » sur votre profil. Commandes et paiements vous arrivent directement.',
  m_link: 'Lien',
  m_notWebAddress: 'Cela ne ressemble pas encore à une adresse web.',
  m_buttonTextOptional: 'Texte du bouton (facultatif)',
  m_buttonTextPlaceholder: 'Par exemple : Rejoignez notre AMAP',
  m_listingNotSent: 'Fiche non envoyée',
  m_sentToBfi: 'Envoyé à BFI',
  m_listingSentBody: 'BFI examinera votre fiche. Vous pouvez ajouter vos produits en attendant.',
  m_listingFreeVerified: 'L’inscription sur l’Index est gratuite. BFI examine chaque ferme avant sa publication et la marque comme vérifiée.',
  m_farmName: 'Nom de la ferme',
  m_cityOrTown: 'Ville ou village',
  m_state: 'État',
  m_bfiRegion: 'Région BFI',
  m_whatGrow: 'Que cultivez-vous ou élevez-vous ?',
  m_storyOptional: 'Votre histoire (facultatif)',
  m_storyPlaceholder: 'Quelques phrases sur votre ferme',
  m_howBuyLines: 'Comment acheter (une par ligne)',
  m_howBuyPlaceholder: 'Stand à la ferme, le samedi\nPaniers AMAP',
  m_howMuchLocation: 'Précision de la position affichée',
  m_cityOnly: 'Ville seulement',
  m_aPickupPoint: 'Un point de retrait',
  m_exactAddress: 'Adresse exacte',
  m_pickupPoint: 'Point de retrait',
  m_pickupPlaceholder: 'Par exemple : marché du samedi, Main St',
  m_addressNeverShown: 'Votre adresse n’est jamais affichée sauf si vous choisissez « {option} ».',
  m_sendForReview: 'Envoyer à BFI pour examen',
  m_profileViews: 'Vues du profil',
  m_followers: 'Abonnés',
  m_inquiries: 'Demandes',
  m_answerOpenInquiry: 'Répondre à 1 demande en attente',
  m_answerOpenInquiries: 'Répondre à {n} demandes en attente',
  m_photosOff: 'Photos désactivées',
  m_allowPhotoAccess: 'Autorisez l’accès aux photos pour The Index dans les réglages du téléphone.',
  m_photoNotAdded: 'Photo non ajoutée',
  m_tryAgainDot: 'Réessayez.',
  m_makeFirst: 'Mettre en premier',
  m_coverPhoto: 'Photo de couverture',
  m_removePhoto: 'Supprimer la photo : {alt}',
  m_selectedPhoto: 'Photo sélectionnée',
  m_describePhoto: 'Décrivez la photo',
  m_describePhotoHint: 'Lu à voix haute pour les personnes qui ne la voient pas. Par exemple : rangs de chou cavalier au lever du soleil.',
  m_photoConsent: 'J’ai pris cette photo ou j’ai l’autorisation, et BFI peut l’afficher dans l’appli',
  m_addPhotoBtn: 'Ajouter la photo',
  m_photosGetVisits: 'Les fermes avec photos reçoivent plus de visites. Votre première photo sert de couverture à votre fiche.',
  m_kindNeed: 'Besoin d’aide',
  m_kindNeedHint: 'Bras pour la récolte, transport au marché, conseils',
  m_kindOffer: 'J’offre',
  m_kindOfferHint: 'Plants, surplus de production, un savoir-faire',
  m_kindEquipment: 'Matériel',
  m_kindEquipmentHint: 'Outils, tracteurs ou chambre froide à prêter ou partager',
  m_kindRide: 'Trajets et transport',
  m_kindRideHint: 'Covoiturage vers les événements, transport partagé',
  m_kindBulk: 'Achats groupés',
  m_kindBulkHint: 'Regroupez les commandes de semences, d’aliments ou d’emballages',
  m_kindMentor: 'Mentorat',
  m_kindMentorHint: 'Proposez ou demandez les conseils d’un autre producteur',
  m_useRealDate: 'Indiquez une vraie date, comme 2026-10-24.',
  m_pickTodayOrLater: 'Choisissez aujourd’hui ou une date ultérieure.',
  m_notPosted: 'Non publié',
  m_whatKindOfPost: 'Quel type de publication ?',
  m_headline: 'Titre',
  m_headlinePlaceholder: 'Besoin de 3 personnes pour la récolte des patates douces',
  m_details: 'Détails',
  m_detailsPlaceholder: 'Quoi, quand, et ce qu’il faut apporter ou savoir',
  m_whereOptional: 'Où (facultatif)',
  m_dateOptional: 'Date (facultatif)',
  m_post: 'Publier',
  m_displayNameShows: 'Votre nom d’affichage apparaît sur la publication. Les gens vous répondent en privé dans Messages.',
  m_evFarmDay: 'Journée à la ferme',
  m_evMarket: 'Marché',
  m_evWorkshop: 'Atelier',
  m_evVolunteer: 'Bénévolat',
  m_evTownHall: 'Réunion publique',
  m_pickFutureDateTime: 'Choisissez une date et une heure pas encore passées.',
  m_use24h: 'Utilisez le format 24 h, comme 10:00 ou 14:30.',
  m_eventNotSent: 'Événement non envoyé',
  m_eventSentBody: 'Votre événement sera visible par tous une fois approuvé par BFI.',
  m_eventsApproved: 'BFI ou un coordinateur régional approuve les événements avant leur publication.',
  m_eventName: 'Nom de l’événement',
  m_eventNamePlaceholder: 'Cueillette de patates douces',
  m_type: 'Type',
  m_dateYmd: 'Date (année-mois-jour)',
  m_startTime: 'Heure de début',
  m_where: 'Où',
  m_detailsOptional: 'Détails (facultatif)',
  m_sendForApproval: 'Envoyer pour approbation',
  m_textSizeHint: 'S’ajoute au réglage de taille du texte de votre téléphone.',
  m_translateHint: 'Les messages et les fiches peuvent être traduits dans votre langue avec le bouton Traduire.',
  m_member: 'Membre',
  m_signedOut: 'Déconnecté',
  m_bfiStaff: 'Équipe BFI',
  m_pushOff: 'Les notifications sont désactivées',
  m_codeNotSent: 'Code non envoyé',
  m_notConfirmed: 'Non confirmé',
  m_codeNoMatch: 'Ce code ne correspond pas',
  m_checkTextTryAgain: 'Vérifiez le SMS et réessayez.',
  m_pushWebHint: 'Disponible dans les applis iPhone et Android.',
  m_turningOn: 'Activation…',
  m_pushHint: 'Réponses, produits frais, rappels et nouvelles de BFI.',
  m_emailHint: 'Rappels d’événements, échéances et annonces de BFI.',
  m_smsIntro: 'Pour les membres qui préfèrent les SMS. Des frais de messagerie peuvent s’appliquer. Répondez STOP à n’importe quel SMS pour vous désabonner.',
  m_confirmNumberCode: 'Confirmez votre numéro. Nous enverrons un code à 6 chiffres au {phone}.',
  m_addNumberFirst: 'Ajoutez d’abord votre numéro',
  m_inboxHint: 'Tout apparaît aussi dans votre boîte de notifications, quels que soient les canaux choisis.',
  m_codeDidNotWork: 'Ce code n’a pas fonctionné',
  m_checkEmailCode: 'Vérifiez le code dans votre e-mail ou demandez-en un nouveau.',
  m_notConfigured: 'Cette version n’est pas encore connectée à une base de données. Consultez le README pour ajouter les réglages Supabase.',
  m_emailCodeIntro: 'Nous vous enverrons un code à 6 chiffres par e-mail. Pas besoin de mot de passe.',
  m_yourName: 'Votre nom',
  m_yourNamePlaceholder: 'Comment vous souhaitez apparaître aux autres',
  m_emailMeCode: 'M’envoyer un code',
  m_enterCodeSentTo: 'Saisissez le code envoyé à {email}.',
  m_sixDigitCode: 'Code à 6 chiffres',
  m_differentEmail: 'Utiliser une autre adresse e-mail',
  m_signInConsent: 'En vous connectant, vous acceptez que BFI vous contacte au sujet de votre compte. Votre e-mail n’est jamais montré aux autres membres.',
  m_messageNotSent: 'Message non envoyé',
  m_conversation: 'Conversation',
  m_viewFarmProfile: 'Voir le profil de la ferme',
  m_noMessages: 'Aucun message pour l’instant.',
  m_channelPostOnly: 'Seuls les producteurs vérifiés et l’équipe BFI peuvent publier dans les canaux.',
  m_readOnlyConversation: 'Vous pouvez lire cette conversation mais pas y répondre.',
  m_you: 'Vous',
  m_replyReady: 'Oui, c’est prêt. À bientôt !',
  m_replyPartial: 'J’en ai une partie cette semaine. Voulez-vous que je vous mette de côté ce que j’ai ?',
  m_replyUnavailable: 'Pas cette semaine, désolé. Je vous écrirai quand ce sera de retour.',
  m_replyNotSent: 'Réponse non envoyée',
  m_reviewMessage: 'Les modérateurs de BFI examineront ce message.',
  m_notHidden: 'Non masqué',
  m_yourInquiry: 'Votre demande',
  m_inquiryFrom: 'Demande de {name}',
  m_farmerReady: 'Le producteur dit : prêt',
  m_farmerPartial: 'Le producteur dit : en partie disponible',
  m_farmerUnavailable: 'Le producteur dit : pas cette semaine',
  m_answerReady: 'Oui, c’est prêt',
  m_answerPartial: 'J’en ai une partie',
  m_answerUnavailable: 'Pas cette semaine',
  m_pinned: 'épinglé',
  m_hiddenByMod: 'masqué par un modérateur',
  m_transcriptComing: 'Transcription en cours…',
  m_hideMessageFrom: 'Masquer le message de {name}',
  m_hide: 'Masquer',
  m_translationUnavailable: 'La traduction n’est pas disponible pour le moment.',
  m_photoCredit: 'Photo : {credit}',
  m_micOff: 'Le micro est désactivé',
  m_allowMic: 'Autorisez l’accès au micro pour The Index dans les réglages du téléphone pour envoyer des messages vocaux.',
  m_recordingNotStarted: 'L’enregistrement n’a pas démarré',
  m_micBusy: 'Une autre appli utilise peut-être le micro. Réessayez dans un instant.',
  m_tooShort: 'Trop court',
  m_holdLonger: 'Attendez un peu plus avant d’arrêter.',
  m_voiceNotSent: 'Message vocal non envoyé',
  m_recordingOneSecond: 'Enregistrement, 1 seconde',
  m_recordingSeconds: 'Enregistrement, {n} secondes',
  m_recordingUnavailable: 'Enregistrement indisponible',
  m_pauseVoice: 'Mettre en pause le message vocal',
  m_playVoice: 'Écouter le message vocal, {length}',
  m_loading: 'Chargement',
};
const ht: Keys = {
  m_errorTitle: 'Gen yon pwoblèm sou ekran sa a',
  m_errorHint: 'Eseye ankò, oswa retounen nan Dekouvri.',
  m_back: 'Retounen',
  m_backTo: 'Retounen nan {label}',
  m_copied: 'Kopye',
  m_quotedOnBfi: '{name} · site sou paj dakèy BFI',
  m_bfiWorksToward: 'Sa BFI ap travay pou li',
  m_howItStarted: 'Kijan sa te kòmanse',
  m_programs: 'Pwogram',
  m_partners: 'Patnè',
  m_foundedBy: 'Fondatè',
  m_contact: 'Kontak',
  m_copy: 'Kopye',
  m_copyItem: 'Kopye {label}',
  m_donate: 'Fè yon don',
  m_shop: 'Boutik',
  m_visitWebsite: 'Vizite sit entènèt la',
  m_contentFrom: 'Kontni soti nan blackfarmersindex.com, verifye 4 okt. 2026.',
  m_choosePlaceFirst: 'Chwazi yon kote anvan',
  m_choosePlaceHint: 'Sèvi ak pozisyon ou oswa antre yon vil pou nou konnen sa “toupre” vle di.',
  m_alertNotSaved: 'Alèt la pa anrejistre',
  m_notRemoved: 'Pa retire',
  m_alertsIntro: 'N ap fè ou konnen lè yon fèm toupre ou make yon bagay fre. Pozisyon ou sove sèlman ak alèt la, e se ou sèl ki ka wè l.',
  m_newAlert: 'Nouvo alèt',
  m_lookingFor: 'Kisa w ap chèche?',
  m_alertPlaceholder: 'Siwo myèl, kalalou, ze poul lib…',
  m_within: 'Nan yon distans',
  m_nMiles: '{n} mil',
  m_saveAlert: 'Sove alèt la',
  m_noAlerts: 'Poko gen alèt.',
  m_withinMilesOf: 'Nan {n} mil de {place}',
  m_yourSavedLocation: 'pozisyon ou sove a',
  m_remove: 'Retire',
  m_locExact: '{city}, {state}. Fèm nan pataje adrès la.',
  m_locPickup: 'Pran l nan {place}. Adrès fèm nan rete prive.',
  m_locCity: '{city}, {state}. Adrès egzak la pataje apre yon kòmand.',
  m_couldNotUpdate: 'Pa t ka mete ajou',
  m_messageNotStarted: 'Mesaj la pa kòmanse',
  m_reportNotSent: 'Rapò a pa voye',
  m_reportSent: 'Rapò a voye',
  m_reviewListing: 'Moderatè BFI yo pral revize fich sa a.',
  m_awaitingVerification: 'Ap tann verifikasyon',
  m_onIndexSince: 'Sou Index la depi {year}.',
  m_onIndexSinceVerified: 'Sou Index la depi {year}, BFI verifye l {date}.',
  m_nothingThisWeek: 'Anyen pa poste semèn sa a. Swiv fèm nan pou w konnen lè gen yon bagay ki rive.',
  m_orderOnFarmSite: 'Sou pwòp sit fèm nan. Kòmand ak peman ale dirèkteman bay fèm nan.',
  m_messageTheFarm: 'Ekri fèm nan',
  m_langsRepliesSms: '{langs}. Reponn pa mesaj tèks.',
  m_website: 'Sit entènèt',
  m_farmNotJoinedNote: 'Fèm sa a sou Index la men li poko antre nan aplikasyon an, kidonk li pa ka resevwa mesaj isit la.',
  m_editMyFarm: 'Modifye fèm mwen',
  m_inquiryNotSent: 'Demann nan pa voye',
  m_toFarm: 'Pou {name}',
  m_whenYmd: 'Kilè (ane-mwa-jou)',
  m_dateHintToday: 'Sèvi ak yon vrè dat apati jodi a, tankou {today}.',
  m_notUpdated: 'Pa mete ajou',
  m_notAdded: 'Pa ajoute',
  m_notSaved: 'Pa sove',
  m_waitingReview: 'Ap tann revizyon BFI',
  m_reviewsNewListing: 'BFI revize chak nouvo fich. Ou ka mete pwodwi ou yo kounye a; fèm ou ap parèt lè yo apwouve l.',
  m_freshTapToggle: 'Sa ki fre semèn sa a · peze pou limen oswa etenn',
  m_addProduct: 'Ajoute yon pwodwi',
  m_addProductPlaceholder: 'Pa egzanp: fèy nave',
  m_add: 'Ajoute',
  m_followersNotified: 'Moun k ap swiv ou yo resevwa yon notifikasyon lè ou make yon bagay fre.',
  m_harvestModeHint: 'Montre achtè yo ou nan rekòt e ou ka pran tan pou reponn.',
  m_acceptMessages: 'Aksepte mesaj achtè yo',
  m_replyByText: 'Mwen reponn pa mesaj tèks',
  m_replyByTextHint: 'Mesaj yo rive jwenn ou pa tèks lè ou limen mesaj tèks nan Paramèt. Reponn tèks la, kòmanse ak kòd ki ladan l (tankou #K7P). Pou yon demann, ajoute YES, PART oswa NO apre kòd la.',
  m_viewPublicProfile: 'Gade pwofil piblik mwen',
  m_orderLinkIntro: 'Ou gen yon boutik sou entènèt, yon enskripsyon CSA oswa yon paj mache? Ajoute l epi achtè yo ap wè yon bouton “{button}” sou pwofil ou. Kòmand ak peman vin jwenn ou dirèkteman.',
  m_link: 'Lyen',
  m_notWebAddress: 'Sa poko sanble yon adrès sit entènèt.',
  m_buttonTextOptional: 'Tèks bouton an (si ou vle)',
  m_buttonTextPlaceholder: 'Pa egzanp: Antre nan CSA nou an',
  m_listingNotSent: 'Fich la pa voye',
  m_sentToBfi: 'Voye bay BFI',
  m_listingSentBody: 'BFI pral revize fich ou. Ou ka ajoute pwodwi ou yo pandan w ap tann.',
  m_listingFreeVerified: 'Mete fèm ou sou Index la gratis. BFI revize chak fèm anvan li parèt epi li make l verifye.',
  m_farmName: 'Non fèm nan',
  m_cityOrTown: 'Vil oswa bouk',
  m_state: 'Eta',
  m_bfiRegion: 'Rejyon BFI',
  m_whatGrow: 'Kisa ou plante oswa ou elve?',
  m_storyOptional: 'Istwa ou (si ou vle)',
  m_storyPlaceholder: 'Kèk fraz sou fèm ou',
  m_howBuyLines: 'Kijan moun ka achte (youn pa liy)',
  m_howBuyPlaceholder: 'Kanpe nan fèm nan, samdi\nBwat CSA',
  m_howMuchLocation: 'Konbyen nan pozisyon ou pou montre',
  m_cityOnly: 'Vil la sèlman',
  m_aPickupPoint: 'Yon kote pou pran',
  m_exactAddress: 'Adrès egzak',
  m_pickupPoint: 'Kote pou pran',
  m_pickupPlaceholder: 'Pa egzanp: mache samdi, Main St',
  m_addressNeverShown: 'Adrès lari ou pa janm parèt sòf si ou chwazi “{option}”.',
  m_sendForReview: 'Voye bay BFI pou revizyon',
  m_profileViews: 'Vizit pwofil',
  m_followers: 'Moun k ap swiv',
  m_inquiries: 'Demann',
  m_answerOpenInquiry: 'Reponn 1 demann ki louvri',
  m_answerOpenInquiries: 'Reponn {n} demann ki louvri',
  m_photosOff: 'Foto yo pa otorize',
  m_allowPhotoAccess: 'Bay The Index aksè a foto yo nan paramèt telefòn ou.',
  m_photoNotAdded: 'Foto a pa ajoute',
  m_tryAgainDot: 'Eseye ankò.',
  m_makeFirst: 'Mete l an premye',
  m_coverPhoto: 'Foto kouvèti',
  m_removePhoto: 'Retire foto: {alt}',
  m_selectedPhoto: 'Foto ou chwazi a',
  m_describePhoto: 'Dekri foto a',
  m_describePhotoHint: 'Yo li l fò pou moun ki pa ka wè l. Pa egzanp: ranje chou vè lè solèy ap leve.',
  m_photoConsent: 'Se mwen ki pran foto sa a oswa mwen gen pèmisyon, e BFI ka montre l nan aplikasyon an',
  m_addPhotoBtn: 'Ajoute foto a',
  m_photosGetVisits: 'Fèm ki gen foto resevwa plis vizit. Premye foto ou se kouvèti fich ou.',
  m_kindNeed: 'Bezwen èd',
  m_kindNeedHint: 'Men pou rekòt, yon woulib pou mache, konsèy',
  m_kindOffer: 'M ap ofri',
  m_kindOfferHint: 'Ti plant, rekòt an plis, yon konpetans',
  m_kindEquipment: 'Ekipman',
  m_kindEquipmentHint: 'Zouti, traktè oswa frijidè pou prete oswa pataje',
  m_kindRide: 'Woulib ak transpò',
  m_kindRideHint: 'Pataje machin pou ale nan evènman, pataje kamyon',
  m_kindBulk: 'Achte ansanm',
  m_kindBulkHint: 'Mete kòmand ansanm pou semans, manje bèt oswa anbalaj',
  m_kindMentor: 'Konsèy ak gid',
  m_kindMentorHint: 'Ofri oswa mande konsèy bay yon lòt kiltivatè',
  m_useRealDate: 'Sèvi ak yon vrè dat, tankou 2026-10-24.',
  m_pickTodayOrLater: 'Chwazi jodi a oswa yon dat pita.',
  m_notPosted: 'Pa pibliye',
  m_whatKindOfPost: 'Ki kalite pòs?',
  m_headline: 'Tit',
  m_headlinePlaceholder: 'Bezwen 3 moun pou rekòt patat',
  m_details: 'Detay',
  m_detailsPlaceholder: 'Kisa, kilè, ak sa moun dwe pote oswa konnen',
  m_whereOptional: 'Ki kote (si ou vle)',
  m_dateOptional: 'Dat (si ou vle)',
  m_post: 'Pibliye',
  m_displayNameShows: 'Non ou parèt sou pòs la. Moun reponn ou an prive nan Mesaj.',
  m_evFarmDay: 'Jounen fèm',
  m_evMarket: 'Mache',
  m_evWorkshop: 'Atelye',
  m_evVolunteer: 'Volontè',
  m_evTownHall: 'Reyinyon kominotè',
  m_pickFutureDateTime: 'Chwazi yon dat ak yon lè ki poko pase.',
  m_use24h: 'Sèvi ak lè 24 èdtan, tankou 10:00 oswa 14:30.',
  m_eventNotSent: 'Evènman an pa voye',
  m_eventSentBody: 'Evènman ou an ap parèt pou tout moun lè BFI apwouve l.',
  m_eventsApproved: 'BFI oswa yon kowòdonatè rejyonal apwouve evènman yo anvan yo parèt.',
  m_eventName: 'Non evènman an',
  m_eventNamePlaceholder: 'Vin keyi pwòp patat ou',
  m_type: 'Kalite',
  m_dateYmd: 'Dat (ane-mwa-jou)',
  m_startTime: 'Lè li kòmanse',
  m_where: 'Ki kote',
  m_detailsOptional: 'Detay (si ou vle)',
  m_sendForApproval: 'Voye pou apwobasyon',
  m_textSizeHint: 'Sa ajoute sou gwosè tèks ou chwazi nan telefòn ou.',
  m_translateHint: 'Ou ka tradui mesaj ak fich yo nan lang ou ak bouton Tradui a.',
  m_member: 'Manm',
  m_signedOut: 'Ou dekonekte',
  m_bfiStaff: 'Ekip BFI',
  m_pushOff: 'Notifikasyon telefòn yo fèmen',
  m_codeNotSent: 'Kòd la pa voye',
  m_notConfirmed: 'Pa konfime',
  m_codeNoMatch: 'Kòd sa a pa koresponn',
  m_checkTextTryAgain: 'Tcheke tèks la epi eseye ankò.',
  m_pushWebHint: 'Disponib nan aplikasyon iPhone ak Android yo.',
  m_turningOn: 'N ap limen…',
  m_pushHint: 'Repons, pwodwi fre, rapèl ak nouvèl BFI.',
  m_emailHint: 'Rapèl evènman, dat limit ak anons BFI.',
  m_smsIntro: 'Pou manm ki pito tèks. Ka gen frè pou mesaj. Reponn STOP nenpòt tèks pou w sispann resevwa yo.',
  m_confirmNumberCode: 'Konfime nimewo ou. N ap voye yon kòd 6 chif bay {phone}.',
  m_addNumberFirst: 'Ajoute nimewo ou anvan',
  m_inboxHint: 'Tout bagay parèt tou nan bwat notifikasyon ou, kèlkeswa chanèl ou chwazi.',
  m_codeDidNotWork: 'Kòd sa a pa mache',
  m_checkEmailCode: 'Tcheke kòd la nan imèl ou, oswa mande yon lòt.',
  m_notConfigured: 'Vèsyon sa a poko konekte ak yon baz done. Gade README a pou ajoute paramèt Supabase yo.',
  m_emailCodeIntro: 'N ap voye yon kòd 6 chif ba ou pa imèl. Ou pa bezwen modpas.',
  m_yourName: 'Non ou',
  m_yourNamePlaceholder: 'Kijan ou vle lòt moun wè non ou',
  m_emailMeCode: 'Voye yon kòd ban mwen',
  m_enterCodeSentTo: 'Antre kòd nou voye bay {email} la.',
  m_sixDigitCode: 'Kòd 6 chif',
  m_differentEmail: 'Sèvi ak yon lòt imèl',
  m_signInConsent: 'Lè ou konekte, ou dakò BFI ka kontakte ou sou kont ou. Lòt manm pa janm wè imèl ou.',
  m_messageNotSent: 'Mesaj la pa voye',
  m_conversation: 'Konvèsasyon',
  m_viewFarmProfile: 'Gade pwofil fèm nan',
  m_noMessages: 'Poko gen mesaj.',
  m_channelPostOnly: 'Se sèlman kiltivatè ki verifye ak ekip BFI ki ka poste nan chanèl yo.',
  m_readOnlyConversation: 'Ou ka li konvèsasyon sa a men ou pa ka reponn.',
  m_you: 'Ou',
  m_replyReady: 'Wi, li pare. N a wè!',
  m_replyPartial: 'Mwen gen yon pati ladan l semèn sa a. Ou vle m kenbe sa m genyen an pou ou?',
  m_replyUnavailable: 'Pa semèn sa a, eskize m. M ap ekri ou lè li tounen.',
  m_replyNotSent: 'Repons lan pa voye',
  m_reviewMessage: 'Moderatè BFI yo pral revize mesaj sa a.',
  m_notHidden: 'Pa kache',
  m_yourInquiry: 'Demann ou',
  m_inquiryFrom: 'Demann {name}',
  m_farmerReady: 'Kiltivatè a di: li pare',
  m_farmerPartial: 'Kiltivatè a di: gen yon pati',
  m_farmerUnavailable: 'Kiltivatè a di: pa semèn sa a',
  m_answerReady: 'Wi, li pare',
  m_answerPartial: 'Mwen gen yon pati',
  m_answerUnavailable: 'Pa semèn sa a',
  m_pinned: 'tache anlè',
  m_hiddenByMod: 'yon moderatè kache l',
  m_transcriptComing: 'Transkripsyon an ap vini…',
  m_hideMessageFrom: 'Kache mesaj {name}',
  m_hide: 'Kache',
  m_translationUnavailable: 'Tradiksyon an pa disponib kounye a.',
  m_photoCredit: 'Foto: {credit}',
  m_micOff: 'Mikwo a fèmen',
  m_allowMic: 'Bay The Index aksè a mikwo a nan paramèt telefòn ou pou voye nòt vokal.',
  m_recordingNotStarted: 'Anrejistreman an pa kòmanse',
  m_micBusy: 'Gen yon lòt aplikasyon ki ka ap sèvi ak mikwo a. Eseye ankò nan yon ti moman.',
  m_tooShort: 'Twò kout',
  m_holdLonger: 'Tann yon ti kras ankò anvan ou kanpe.',
  m_voiceNotSent: 'Nòt vokal la pa voye',
  m_recordingOneSecond: 'Ap anrejistre, 1 segonn',
  m_recordingSeconds: 'Ap anrejistre, {n} segonn',
  m_recordingUnavailable: 'Anrejistreman an pa disponib',
  m_pauseVoice: 'Poze nòt vokal la',
  m_playVoice: 'Jwe nòt vokal la, {length}',
  m_loading: 'Ap chaje',
};
const pt: Keys = {
  m_errorTitle: 'Algo deu errado nesta tela',
  m_errorHint: 'Tente de novo ou volte para Descobrir.',
  m_back: 'Voltar',
  m_backTo: 'Voltar para {label}',
  m_copied: 'Copiado',
  m_quotedOnBfi: '{name} · citado na página inicial do BFI',
  m_bfiWorksToward: 'O que o BFI busca',
  m_howItStarted: 'Como começou',
  m_programs: 'Programas',
  m_partners: 'Parceiros',
  m_foundedBy: 'Fundado por',
  m_contact: 'Contato',
  m_copy: 'Copiar',
  m_copyItem: 'Copiar {label}',
  m_donate: 'Doar',
  m_shop: 'Loja',
  m_visitWebsite: 'Visitar o site',
  m_contentFrom: 'Conteúdo de blackfarmersindex.com, verificado em 4 de out. de 2026.',
  m_choosePlaceFirst: 'Escolha um lugar primeiro',
  m_choosePlaceHint: 'Use sua localização ou digite uma cidade para sabermos o que é “perto”.',
  m_alertNotSaved: 'Alerta não salvo',
  m_notRemoved: 'Não removido',
  m_alertsIntro: 'Avisaremos quando uma fazenda perto de você marcar algo fresco. Sua localização fica salva só com o alerta, e só você pode vê-la.',
  m_newAlert: 'Novo alerta',
  m_lookingFor: 'O que você procura?',
  m_alertPlaceholder: 'Mel, quiabo, ovos caipiras…',
  m_within: 'Num raio de',
  m_nMiles: '{n} milhas',
  m_saveAlert: 'Salvar alerta',
  m_noAlerts: 'Nenhum alerta ainda.',
  m_withinMilesOf: 'Até {n} milhas de {place}',
  m_yourSavedLocation: 'sua localização salva',
  m_remove: 'Remover',
  m_locExact: '{city}, {state}. Endereço compartilhado pela fazenda.',
  m_locPickup: 'Retirada em {place}. O endereço da fazenda fica privado.',
  m_locCity: '{city}, {state}. Endereço exato compartilhado após o pedido.',
  m_couldNotUpdate: 'Não foi possível atualizar',
  m_messageNotStarted: 'Mensagem não iniciada',
  m_reportNotSent: 'Denúncia não enviada',
  m_reportSent: 'Denúncia enviada',
  m_reviewListing: 'Os moderadores do BFI vão analisar este perfil.',
  m_awaitingVerification: 'Aguardando verificação',
  m_onIndexSince: 'No Index desde {year}.',
  m_onIndexSinceVerified: 'No Index desde {year}, verificada pelo BFI em {date}.',
  m_nothingThisWeek: 'Nada publicado esta semana. Siga a fazenda para saber quando chegar algo.',
  m_orderOnFarmSite: 'No site da própria fazenda. Pedidos e pagamentos vão direto para a fazenda.',
  m_messageTheFarm: 'Mande mensagem para a fazenda',
  m_langsRepliesSms: '{langs}. Responde por SMS.',
  m_website: 'Site',
  m_farmNotJoinedNote: 'Esta fazenda está no Index, mas ainda não entrou no app, então não pode receber mensagens aqui.',
  m_editMyFarm: 'Editar minha fazenda',
  m_inquiryNotSent: 'Pedido não enviado',
  m_toFarm: 'Para {name}',
  m_whenYmd: 'Quando (ano-mês-dia)',
  m_dateHintToday: 'Use uma data real a partir de hoje, como {today}.',
  m_notUpdated: 'Não atualizado',
  m_notAdded: 'Não adicionado',
  m_notSaved: 'Não salvo',
  m_waitingReview: 'Aguardando análise do BFI',
  m_reviewsNewListing: 'O BFI analisa cada novo perfil. Você já pode cadastrar seus produtos; sua fazenda entra no ar quando for aprovada.',
  m_freshTapToggle: 'O que tem fresco esta semana · toque para ativar ou desativar',
  m_addProduct: 'Adicionar um produto',
  m_addProductPlaceholder: 'Por exemplo: folhas de nabo',
  m_add: 'Adicionar',
  m_followersNotified: 'Seus seguidores recebem uma notificação quando você marca algo como fresco.',
  m_harvestModeHint: 'Mostra aos compradores que você está na colheita e pode demorar para responder.',
  m_acceptMessages: 'Aceitar mensagens de compradores',
  m_replyByText: 'Respondo por SMS',
  m_replyByTextHint: 'As mensagens chegam por SMS quando você ativa os SMS em Configurações. Responda ao SMS começando pelo código que vem nele (como #K7P). Para um pedido, adicione YES, PART ou NO depois do código.',
  m_viewPublicProfile: 'Ver meu perfil público',
  m_orderLinkIntro: 'Tem loja on-line, inscrição em CSA ou página de feira? Adicione e os compradores verão um botão “{button}” no seu perfil. Pedidos e pagamentos vão direto para você.',
  m_link: 'Link',
  m_notWebAddress: 'Isso ainda não parece um endereço da web.',
  m_buttonTextOptional: 'Texto do botão (opcional)',
  m_buttonTextPlaceholder: 'Por exemplo: Entre na nossa CSA',
  m_listingNotSent: 'Perfil não enviado',
  m_sentToBfi: 'Enviado ao BFI',
  m_listingSentBody: 'O BFI vai analisar seu perfil. Você pode adicionar seus produtos enquanto espera.',
  m_listingFreeVerified: 'Estar no Index é grátis. O BFI analisa cada fazenda antes de publicá-la e a marca como verificada.',
  m_farmName: 'Nome da fazenda',
  m_cityOrTown: 'Cidade',
  m_state: 'Estado',
  m_bfiRegion: 'Região do BFI',
  m_whatGrow: 'O que você cultiva ou cria?',
  m_storyOptional: 'Sua história (opcional)',
  m_storyPlaceholder: 'Algumas frases sobre sua fazenda',
  m_howBuyLines: 'Como as pessoas podem comprar (uma por linha)',
  m_howBuyPlaceholder: 'Barraca na fazenda, aos sábados\nCestas CSA',
  m_howMuchLocation: 'Quanto da localização mostrar',
  m_cityOnly: 'Só a cidade',
  m_aPickupPoint: 'Um ponto de retirada',
  m_exactAddress: 'Endereço exato',
  m_pickupPoint: 'Ponto de retirada',
  m_pickupPlaceholder: 'Por exemplo: feira de sábado, Main St',
  m_addressNeverShown: 'Seu endereço nunca aparece, a menos que você escolha “{option}”.',
  m_sendForReview: 'Enviar ao BFI para análise',
  m_profileViews: 'Visitas ao perfil',
  m_followers: 'Seguidores',
  m_inquiries: 'Pedidos',
  m_answerOpenInquiry: 'Responder 1 pedido em aberto',
  m_answerOpenInquiries: 'Responder {n} pedidos em aberto',
  m_photosOff: 'Fotos desativadas',
  m_allowPhotoAccess: 'Permita o acesso às fotos para The Index nas configurações do celular.',
  m_photoNotAdded: 'Foto não adicionada',
  m_tryAgainDot: 'Tente de novo.',
  m_makeFirst: 'Colocar primeiro',
  m_coverPhoto: 'Foto de capa',
  m_removePhoto: 'Remover foto: {alt}',
  m_selectedPhoto: 'Foto selecionada',
  m_describePhoto: 'Descreva a foto',
  m_describePhotoHint: 'Lida em voz alta para quem não pode vê-la. Por exemplo: fileiras de couve ao nascer do sol.',
  m_photoConsent: 'Tirei esta foto ou tenho permissão, e o BFI pode mostrá-la no app',
  m_addPhotoBtn: 'Adicionar foto',
  m_photosGetVisits: 'Fazendas com fotos recebem mais visitas. Sua primeira foto é a capa do seu perfil.',
  m_kindNeed: 'Preciso de ajuda',
  m_kindNeedHint: 'Ajuda na colheita, carona para a feira, conselhos',
  m_kindOffer: 'Ofereço',
  m_kindOfferHint: 'Mudas, sobra de produção, uma habilidade',
  m_kindEquipment: 'Equipamentos',
  m_kindEquipmentHint: 'Ferramentas, tratores ou câmara fria para emprestar ou dividir',
  m_kindRide: 'Caronas e fretes',
  m_kindRideHint: 'Caronas para eventos, frete compartilhado',
  m_kindBulk: 'Compras em grupo',
  m_kindBulkHint: 'Juntem pedidos de sementes, ração ou embalagens',
  m_kindMentor: 'Mentoria',
  m_kindMentorHint: 'Ofereça ou peça orientação a outro produtor',
  m_useRealDate: 'Use uma data real, como 2026-10-24.',
  m_pickTodayOrLater: 'Escolha hoje ou uma data posterior.',
  m_notPosted: 'Não publicado',
  m_whatKindOfPost: 'Que tipo de publicação?',
  m_headline: 'Título',
  m_headlinePlaceholder: 'Preciso de 3 pessoas para colher batata-doce',
  m_details: 'Detalhes',
  m_detailsPlaceholder: 'O quê, quando e o que as pessoas devem levar ou saber',
  m_whereOptional: 'Onde (opcional)',
  m_dateOptional: 'Data (opcional)',
  m_post: 'Publicar',
  m_displayNameShows: 'Seu nome de exibição aparece na publicação. As pessoas respondem a você em particular em Mensagens.',
  m_evFarmDay: 'Dia na fazenda',
  m_evMarket: 'Feira',
  m_evWorkshop: 'Oficina',
  m_evVolunteer: 'Voluntariado',
  m_evTownHall: 'Reunião comunitária',
  m_pickFutureDateTime: 'Escolha uma data e hora que ainda não passaram.',
  m_use24h: 'Use o formato de 24 horas, como 10:00 ou 14:30.',
  m_eventNotSent: 'Evento não enviado',
  m_eventSentBody: 'Seu evento vai aparecer para todos quando o BFI aprovar.',
  m_eventsApproved: 'O BFI ou um coordenador regional aprova os eventos antes de serem publicados.',
  m_eventName: 'Nome do evento',
  m_eventNamePlaceholder: 'Colha sua batata-doce',
  m_type: 'Tipo',
  m_dateYmd: 'Data (ano-mês-dia)',
  m_startTime: 'Horário de início',
  m_where: 'Onde',
  m_detailsOptional: 'Detalhes (opcional)',
  m_sendForApproval: 'Enviar para aprovação',
  m_textSizeHint: 'Isso se soma ao tamanho de texto do seu celular.',
  m_translateHint: 'Mensagens e perfis podem ser traduzidos para o seu idioma com o botão Traduzir.',
  m_member: 'Membro',
  m_signedOut: 'Você saiu',
  m_bfiStaff: 'Equipe do BFI',
  m_pushOff: 'As notificações estão desativadas',
  m_codeNotSent: 'Código não enviado',
  m_notConfirmed: 'Não confirmado',
  m_codeNoMatch: 'Esse código não confere',
  m_checkTextTryAgain: 'Confira o SMS e tente de novo.',
  m_pushWebHint: 'Disponível nos apps para iPhone e Android.',
  m_turningOn: 'Ativando…',
  m_pushHint: 'Respostas, produtos frescos, lembretes e novidades do BFI.',
  m_emailHint: 'Lembretes de eventos, prazos e avisos do BFI.',
  m_smsIntro: 'Para quem prefere SMS. Podem ser cobradas tarifas de mensagem. Responda STOP a qualquer SMS para cancelar.',
  m_confirmNumberCode: 'Confirme seu número. Vamos enviar um código de 6 dígitos para {phone}.',
  m_addNumberFirst: 'Adicione seu número primeiro',
  m_inboxHint: 'Tudo também aparece na sua caixa de notificações, seja qual for o canal escolhido.',
  m_codeDidNotWork: 'Esse código não funcionou',
  m_checkEmailCode: 'Confira o código no seu e-mail ou peça um novo.',
  m_notConfigured: 'Esta versão ainda não está conectada a um banco de dados. Veja o README para adicionar as configurações do Supabase.',
  m_emailCodeIntro: 'Vamos enviar um código de 6 dígitos por e-mail. Sem senha.',
  m_yourName: 'Seu nome',
  m_yourNamePlaceholder: 'Como você quer aparecer para os outros',
  m_emailMeCode: 'Enviar um código por e-mail',
  m_enterCodeSentTo: 'Digite o código que enviamos para {email}.',
  m_sixDigitCode: 'Código de 6 dígitos',
  m_differentEmail: 'Usar outro e-mail',
  m_signInConsent: 'Ao entrar, você concorda que o BFI pode entrar em contato sobre sua conta. Seu e-mail nunca é mostrado a outros membros.',
  m_messageNotSent: 'Mensagem não enviada',
  m_conversation: 'Conversa',
  m_viewFarmProfile: 'Ver perfil da fazenda',
  m_noMessages: 'Nenhuma mensagem ainda.',
  m_channelPostOnly: 'Só produtores verificados e a equipe do BFI podem publicar nos canais.',
  m_readOnlyConversation: 'Você pode ler esta conversa, mas não responder.',
  m_you: 'Você',
  m_replyReady: 'Sim, está pronto. Até lá!',
  m_replyPartial: 'Tenho parte disso esta semana. Quer que eu separe o que tenho?',
  m_replyUnavailable: 'Esta semana não, desculpe. Aviso você quando voltar a ter.',
  m_replyNotSent: 'Resposta não enviada',
  m_reviewMessage: 'Os moderadores do BFI vão analisar esta mensagem.',
  m_notHidden: 'Não ocultada',
  m_yourInquiry: 'Seu pedido',
  m_inquiryFrom: 'Pedido de {name}',
  m_farmerReady: 'O produtor diz: pronto',
  m_farmerPartial: 'O produtor diz: disponível em parte',
  m_farmerUnavailable: 'O produtor diz: esta semana não',
  m_answerReady: 'Sim, está pronto',
  m_answerPartial: 'Tenho uma parte',
  m_answerUnavailable: 'Esta semana não',
  m_pinned: 'fixada',
  m_hiddenByMod: 'ocultada por um moderador',
  m_transcriptComing: 'Transcrição a caminho…',
  m_hideMessageFrom: 'Ocultar mensagem de {name}',
  m_hide: 'Ocultar',
  m_translationUnavailable: 'A tradução não está disponível agora.',
  m_photoCredit: 'Foto: {credit}',
  m_micOff: 'O microfone está desativado',
  m_allowMic: 'Permita o acesso ao microfone para The Index nas configurações do celular para enviar áudios.',
  m_recordingNotStarted: 'A gravação não começou',
  m_micBusy: 'Outro app pode estar usando o microfone. Tente de novo em instantes.',
  m_tooShort: 'Muito curto',
  m_holdLonger: 'Espere um pouco mais antes de parar.',
  m_voiceNotSent: 'Áudio não enviado',
  m_recordingOneSecond: 'Gravando, 1 segundo',
  m_recordingSeconds: 'Gravando, {n} segundos',
  m_recordingUnavailable: 'Gravação indisponível',
  m_pauseVoice: 'Pausar áudio',
  m_playVoice: 'Ouvir áudio, {length}',
  m_loading: 'Carregando',
};

export default { en, es, fr, ht, pt };
