// Strings for the "staff" screens (check-ins, announcements, surveys, review, impact) and the shared lib
// helpers (errors, dates, location, push, community post kinds, BFI facts).
// Every key in `en` must exist in es, fr, ht and pt (the types enforce it).
// Placeholders like {n} are filled by t('key', { n: 3 }).
const en = {
  // Shared
  s_open: 'Open',
  s_closed: 'Closed',
  s_openAction: 'Open',
  s_surveyOpenPill: 'Open',
  s_surveyClosedPill: 'Closed',
  s_draft: 'Draft',
  s_refresh: 'Refresh',
  s_notSent: 'Not sent',
  s_notSaved: 'Not saved',
  s_sent: 'Sent',
  s_title: 'Title',
  s_message: 'Message',
  s_messageOptional: 'Message (optional)',
  s_reviewAndSend: 'Review and send',
  s_sendNow: 'Send now',
  s_edit: 'Edit',
  s_confirmSendTo: 'Send “{title}” to {audience}?',
  s_results: 'Results',

  // errors.ts
  s_errGeneric: 'Something went wrong. Try again in a moment.',
  s_errNotFound: 'We couldn’t find that. It may have been removed or is no longer public.',
  s_errOffline: 'You’re offline or the connection dropped. Try again when you have signal.',
  s_errFileType: 'That kind of file can’t be uploaded here. Use a photo (JPEG, PNG, WebP or HEIC).',
  s_errTooBig: 'That file is too big. Try a smaller photo or a shorter recording.',
  s_errNoAccess: 'You don’t have access to do that. Try signing in again.',
  s_errServer: 'Something went wrong on our side. Try again in a moment.',

  // format.ts
  s_updatedToday: 'Updated today',
  s_updatedYesterday: 'Updated yesterday',
  s_updatedDaysAgo: 'Updated {n} days ago',
  s_updatedOn: 'Updated {date}',

  // location.ts
  s_locOff: 'Location is off for The Index. You can still browse by region.',
  s_locFailed: 'Could not find your location.',
  s_geoNotFound: 'Couldn’t find “{place}”. Try a town and state, or a ZIP code.',
  s_geoUnavailable: 'Looking up places by name isn’t available on this device. Use your location instead.',

  // push.ts
  s_pushWeb: 'Phone notifications work in the iPhone and Android apps.',
  s_pushSimulator: 'Phone notifications need a real phone, not a simulator.',
  s_pushExpoGo: 'Phone notifications need the installed app. They are not available in Expo Go on Android.',
  s_pushOff: 'Notifications are turned off for The Index in your phone settings.',
  s_pushNoProject: 'This build is missing its EAS project id. See docs/NOTIFICATIONS.md.',
  s_pushUnreachable: 'Could not reach the notification service. Try again later.',

  // board.ts (community post kinds)
  s_kindNeed: 'Need help',
  s_kindNeedHint: 'Harvest hands, a ride to market, advice',
  s_kindOffer: 'Offering',
  s_kindOfferHint: 'Seedlings, surplus produce, a skill',
  s_kindEquipment: 'Equipment',
  s_kindEquipmentHint: 'Tools, tractors or cold storage to lend or share',
  s_kindRide: 'Rides and hauling',
  s_kindRideHint: 'Carpools to events, shared trucking',
  s_kindBulk: 'Buying together',
  s_kindBulkHint: 'Pool orders for seed, feed or packaging',
  s_kindMentor: 'Mentoring',
  s_kindMentorHint: 'Offer or ask for guidance from another grower',

  // survey.ts (question types)
  s_qtSingle: 'Pick one',
  s_qtMulti: 'Pick any',
  s_qtScale: '1 to 5',
  s_qtText: 'Written answer',

  // bfi.ts
  s_bfiTagline: 'The largest free directory of Black farmers',
  s_bfiStatus: '501(c)(3) nonprofit · Lafayette, LA',
  s_bfiStatGrowers: 'growers listed',
  s_bfiStatWomen: 'women-owned farms',
  s_bfiStatOrganic: 'organic, natural or regenerative',
  s_bfiPillar1: 'Increase marketing toward the Black agricultural ecosystem',
  s_bfiPillar2: 'Collect and share accurate information on Black growers',
  s_bfiPillar3: 'Provide resources for access to capital',
  s_bfiPillar4: 'Advocate for pathways to farmland',
  s_bfiTimeline1: 'First list of Black farmers published as a solutions-journalism project on Ark Republic',
  s_bfiTimeline2: 'Established as a nonprofit',
  s_bfiTimeline3: 'Granted 501(c)(3) status',
  s_bfiTimeline4: 'Awarded SARE grants',
  s_bfiTimeline5: 'Awarded JustFund grant',
  s_bfiProgram1: 'Free online directory',
  s_bfiProgram2: 'Workshops',
  s_bfiProgram3: 'Food-centered events',
  s_bfiProgram4: 'Curated gift boxes',
  s_bfiProgram5: 'Farm visits and feature stories',
  s_bfiProgram6: 'Data gathering and reporting',
  s_bfiFounder: 'Dr. Kaia Niambi Shivers, President and Founder',
  s_bfiContactGeneral: 'General inquiries',
  s_bfiContactCollab: 'Collaborations',
  s_bfiContactDonor: 'Donor opportunities',
  s_bfiContactPress: 'Press and media',
  s_bfiContactPhone: 'Phone',
  s_bfiContactMail: 'Mail',

  // checkin/[id]
  s_checkinMissing: 'This check-in isn’t for your area, or it has been removed.',
  s_checkinMetaOpen: 'From BFI · {date} · open until {until}',
  s_checkinMetaClosed: 'From BFI · {date} · closed',
  s_youAnswered: 'You answered: {answer}.',
  s_checkinClosedEmpty: 'This check-in has closed. If you still need help, message BFI.',
  s_sentCanChange: 'Sent {when} · you can change it below',
  s_sentByTextCanChange: 'Sent {when} by text message · you can change it below',
  s_needPlaceholder: 'For example: a chainsaw to clear the road, a generator for the cooler, help moving animals',
  s_needPrivacy: 'BFI staff will see your name, this note and the phone number in your settings so they can call you.',
  s_checkinResults: 'Results (BFI staff only)',
  s_statNeedHelp: 'need help',
  s_statOk: 'are OK',
  s_statNoAnswer: 'haven’t answered',
  s_byTextShort: 'by text',
  s_noDetails: 'No details given.',
  s_call: 'Call',
  s_text: 'Text',
  s_noPhone: 'No phone number on file. Message them in the app.',
  s_noOneNeedsHelp: 'No one has asked for help yet.',

  // checkins
  s_checkinsStaffOnly: 'Only BFI staff can see check-in results.',
  s_noCheckins: 'No check-ins yet. Send one after a storm, flood, fire or hard freeze.',
  s_audienceSentOn: '{audience} · sent {date}',

  // compose-broadcast
  s_broadcastStaffOnly: 'Only BFI staff can send announcements.',
  s_chPush: 'Phone notification',
  s_chEmail: 'Email',
  s_chSms: 'Text message',
  s_chPushInline: 'phone notification',
  s_chEmailInline: 'email',
  s_chSmsInline: 'text message',
  s_broadcastGoing: 'Your announcement is going out to {audience}.',
  s_broadcastIntro: 'Announcements appear under Messages → From BFI and go out on the channels you pick. Members can turn each channel off.',
  s_broadcastTitlePlaceholder: 'Collard Green Gala tickets',
  s_broadcastBodyPlaceholder: 'Keep it short. Texts are cut at about 280 characters.',
  s_linkOptional: 'Link (optional)',
  s_linkLabel: 'Link label',
  s_linkLabelPlaceholder: 'Get tickets',
  s_linkHttps: 'Links must start with https://',
  s_howSent: 'How it’s sent',
  s_smsCost: 'Text messages cost money per message. Use them for urgent or important news.',
  s_byChannels: 'By {channels}. This can’t be unsent.',
  s_inboxOnly: 'In the app inbox only. This can’t be unsent.',

  // impact
  s_impactStaffOnly: 'Only BFI staff can see the impact report.',
  s_impDirectory: 'Directory',
  s_impBusiness: 'Business for farmers',
  s_impCommunity: 'Community',
  s_impEvents: 'Events and resources',
  s_imp_farms_live: 'Farms live on the Index',
  s_imp_farms_verified: 'Verified by BFI',
  s_imp_farms_on_app: 'Farms reachable in the app',
  s_imp_farms_pending: 'Waiting for review',
  s_imp_inquiries_total: 'Inquiries sent to farms, all time',
  s_imp_inquiries_30d: 'Inquiries, last 30 days',
  s_imp_inquiries_answered: 'Inquiries farmers said yes to',
  s_imp_profile_views_30d: 'Farm profile views, last 30 days',
  s_imp_follows: 'Farms followed',
  s_imp_members: 'Members',
  s_imp_growers: 'Growers',
  s_imp_messages_30d: 'Messages, last 30 days',
  s_imp_board_posts_open: 'Open community board posts',
  s_imp_events_upcoming: 'Upcoming events',
  s_imp_rsvps: 'RSVPs',
  s_imp_volunteer_signups: 'Volunteer sign-ups',
  s_imp_programs_saved: 'Programs saved to deadline trackers',
  s_impactReportTitle: 'The Index impact report',
  s_impactReportMessage: 'The Index impact report, {date}',
  s_couldNotShare: 'Could not share',
  s_asOf: 'As of {date} · sample data excluded',
  s_shareCsv: 'Share as CSV',
  s_farmsByRegion: 'Farms by region',
  s_farmsInRegion: 'Farms in {region}',
  s_regionFarmsOne: '{region}: 1 farm',
  s_regionFarmsN: '{region}: {n} farms',

  // review
  s_reviewStaffOnly: 'Only BFI staff and regional coordinators can see the review queue.',
  s_newListings: 'New farm listings · {n}',
  s_noListings: 'No listings waiting.',
  s_approveVerify: 'Approve and verify',
  s_decline: 'Decline',
  s_approve: 'Approve',
  s_eventsCount: 'Events · {n}',
  s_noEventsWaiting: 'No events waiting.',
  s_reportsCount: 'Reports · {n}',
  s_noOpenReports: 'No open reports.',
  s_openListing: 'Open listing',
  s_markResolved: 'Mark resolved',
  s_target_farm: 'Farm listing',
  s_target_message: 'Message',
  s_target_event: 'Event',
  s_target_profile: 'Profile',
  s_target_post: 'Community post',

  // send-checkin
  s_sendCheckinStaffOnly: 'Only BFI staff can send check-ins.',
  s_checkinIntro:
    'Everyone in the area gets a phone notification and, if they’ve opted in, a text. They answer “I’m OK” or “I need help” in one tap, or by replying SAFE or NEED to the text. You’ll see who needs help, with their phone number, as answers come in.',
  s_checkinPlaceholder: 'Hurricane Delta came through southwest Louisiana last night. Let us know how you and your farm are doing.',
  s_whichArea: 'Which area',
  s_keepOpenFor: 'Keep it open for',
  s_nDays: '{n} days',
  s_checkinChannels: 'By phone notification and text message. Texts cost money per message. This can’t be unsent.',

  // survey/[id]
  s_surveyMissing: 'This survey isn’t for you, or it has been removed.',
  s_surveyFromBfi: 'Survey from BFI',
  s_questionsOne: '1 question',
  s_questionsN: '{n} questions',
  s_openUntil: 'open until {date}',
  s_draftStaffOnly: 'draft, only staff can see it',
  s_seeResults: 'See results',
  s_oneMore: 'One more',
  s_pleaseAnswer: 'Please answer: {question}',
  s_notRemoved: 'Not removed',
  s_thanksAnswers: 'Thank you. Your answers are in.',
  s_canChangeUntilClose: 'You can change them until the survey closes.',
  s_surveyClosed: 'This survey has closed.',
  s_howBfiUses: 'How BFI uses your answers',
  s_howBfiUsesBody:
    'BFI staff can see your answers with your name, so they can follow up if you ask for help. In reports and when speaking up for growers, BFI shares totals only. Your written answers are never quoted unless you say yes below, and even then without your name.',
  s_consentQuote: 'BFI may quote my written answers without my name',
  s_updateAnswers: 'Update my answers',
  s_withdrawAnswers: 'Withdraw my answers',
  s_scaleHint: '1 is poor, 5 is excellent',
  s_pickAnyHint: 'Pick any that apply',

  // survey-builder
  s_builderStaffOnly: 'Only BFI staff can write surveys.',
  s_needTitle: 'Add a title.',
  s_needQuestion: 'Add at least one question.',
  s_needWording: 'Every question needs wording.',
  s_needChoices: 'Pick-one and pick-any questions need at least two choices.',
  s_builderIntro: 'Members get a phone notification and email when the survey opens. Keep it short: five questions or fewer gets the most answers.',
  s_surveyTitlePlaceholder: '2026 growing season check-in',
  s_whyAsking: 'Why you’re asking (shown at the top)',
  s_whyAskingPlaceholder: 'Your answers help BFI make the case for cold storage funding in the next farm bill.',
  s_openFor: 'Open for',
  s_weekOne: '1 week',
  s_weeksN: '{n} weeks',
  s_questions: 'Questions',
  s_question: 'Question',
  s_questionN: 'Question {n}',
  s_up: 'Up',
  s_down: 'Down',
  s_remove: 'Remove',
  s_moveUpA11y: 'Move question {n} up',
  s_moveDownA11y: 'Move question {n} down',
  s_removeA11y: 'Remove question {n}',
  s_choicesPerLine: 'Choices, one per line',
  s_required: 'Required',
  s_addQuestion: 'Add a question',
  s_goesTo: 'Goes to {audience} for {duration}. Answers stay private to BFI staff; written answers are only quoted when the member agrees.',
  s_openSurveyNow: 'Open survey now',
  s_saveDraft: 'Save as draft',

  // survey-results
  s_resultsStaffOnly: 'Only BFI staff can see survey results.',
  s_notChanged: 'Not changed',
  s_copied: 'Copied',
  s_copiedBody: 'The results are on your clipboard. Paste them into a spreadsheet.',
  s_closesOn: 'closes {date}',
  s_responsesOne: '1 response',
  s_responsesN: '{n} responses',
  s_mayBeQuoted: '{n} may be quoted',
  s_openSurvey: 'Open survey',
  s_closeSurvey: 'Close survey',
  s_downloadCsv: 'Download CSV',
  s_csvNote: 'The CSV has no names. Written answers from members who didn’t agree to be quoted are marked “(not shared)”.',
  s_answeredOf: '{n} of {total} answered',
  s_averageOf: 'average {avg} of 5',
  s_withheldOne: '1 more written answer not shown: that member didn’t agree to be quoted.',
  s_withheldN: '{n} more written answers not shown: those members didn’t agree to be quoted.',

  // surveys
  s_surveysIntro: 'BFI asks members a few questions now and then. Totals help them speak up for Black growers with funders and lawmakers.',
  s_writeSurvey: 'Write a survey',
  s_noSurveys: 'No surveys right now.',
  s_answered: 'Answered',
  s_untilDate: 'until {date}',
};
type Keys = Record<keyof typeof en, string>;

const es: Keys = {
  s_open: 'Abierto',
  s_closed: 'Cerrado',
  s_openAction: 'Abrir',
  s_surveyOpenPill: 'Abierta',
  s_surveyClosedPill: 'Cerrada',
  s_draft: 'Borrador',
  s_refresh: 'Actualizar',
  s_notSent: 'No se envió',
  s_notSaved: 'No se guardó',
  s_sent: 'Enviado',
  s_title: 'Título',
  s_message: 'Mensaje',
  s_messageOptional: 'Mensaje (opcional)',
  s_reviewAndSend: 'Revisar y enviar',
  s_sendNow: 'Enviar ahora',
  s_edit: 'Editar',
  s_confirmSendTo: '¿Enviar “{title}” a {audience}?',
  s_results: 'Resultados',

  s_errGeneric: 'Algo salió mal. Inténtalo de nuevo en un momento.',
  s_errNotFound: 'No lo encontramos. Puede que lo hayan quitado o que ya no sea público.',
  s_errOffline: 'No tienes conexión o se cortó. Inténtalo de nuevo cuando tengas señal.',
  s_errFileType: 'Ese tipo de archivo no se puede subir aquí. Usa una foto (JPEG, PNG, WebP o HEIC).',
  s_errTooBig: 'Ese archivo es demasiado grande. Prueba con una foto más pequeña o una grabación más corta.',
  s_errNoAccess: 'No tienes permiso para hacer eso. Intenta iniciar sesión de nuevo.',
  s_errServer: 'Algo salió mal de nuestro lado. Inténtalo de nuevo en un momento.',

  s_updatedToday: 'Actualizado hoy',
  s_updatedYesterday: 'Actualizado ayer',
  s_updatedDaysAgo: 'Actualizado hace {n} días',
  s_updatedOn: 'Actualizado el {date}',

  s_locOff: 'La ubicación está desactivada para The Index. Aún puedes buscar por región.',
  s_locFailed: 'No pudimos encontrar tu ubicación.',
  s_geoNotFound: 'No encontramos “{place}”. Prueba con un pueblo y estado, o un código postal.',
  s_geoUnavailable: 'Buscar lugares por nombre no está disponible en este dispositivo. Usa tu ubicación.',

  s_pushWeb: 'Las notificaciones funcionan en las apps de iPhone y Android.',
  s_pushSimulator: 'Las notificaciones necesitan un teléfono real, no un simulador.',
  s_pushExpoGo: 'Las notificaciones necesitan la app instalada. No están disponibles en Expo Go en Android.',
  s_pushOff: 'Las notificaciones de The Index están desactivadas en los ajustes de tu teléfono.',
  s_pushNoProject: 'A esta versión le falta el id del proyecto de EAS. Consulta docs/NOTIFICATIONS.md.',
  s_pushUnreachable: 'No pudimos conectar con el servicio de notificaciones. Inténtalo más tarde.',

  s_kindNeed: 'Necesito ayuda',
  s_kindNeedHint: 'Manos para la cosecha, transporte al mercado, consejos',
  s_kindOffer: 'Ofrezco',
  s_kindOfferHint: 'Plántulas, excedentes de cosecha, una habilidad',
  s_kindEquipment: 'Equipo',
  s_kindEquipmentHint: 'Herramientas, tractores o cámaras frías para prestar o compartir',
  s_kindRide: 'Viajes y transporte',
  s_kindRideHint: 'Viajes compartidos a eventos, camiones compartidos',
  s_kindBulk: 'Compras en grupo',
  s_kindBulkHint: 'Juntar pedidos de semilla, alimento o empaque',
  s_kindMentor: 'Mentoría',
  s_kindMentorHint: 'Ofrece o pide orientación a otro productor',

  s_qtSingle: 'Elegir una',
  s_qtMulti: 'Elegir varias',
  s_qtScale: 'Del 1 al 5',
  s_qtText: 'Respuesta escrita',

  s_bfiTagline: 'El directorio gratuito más grande de agricultores negros',
  s_bfiStatus: 'Organización sin fines de lucro 501(c)(3) · Lafayette, LA',
  s_bfiStatGrowers: 'productores en la lista',
  s_bfiStatWomen: 'fincas de mujeres',
  s_bfiStatOrganic: 'orgánicas, naturales o regenerativas',
  s_bfiPillar1: 'Aumentar el mercadeo hacia el ecosistema agrícola negro',
  s_bfiPillar2: 'Reunir y compartir información precisa sobre productores negros',
  s_bfiPillar3: 'Ofrecer recursos para acceder a capital',
  s_bfiPillar4: 'Abogar por caminos hacia la tierra agrícola',
  s_bfiTimeline1: 'Se publica la primera lista de agricultores negros como proyecto de periodismo de soluciones en Ark Republic',
  s_bfiTimeline2: 'Se constituye como organización sin fines de lucro',
  s_bfiTimeline3: 'Recibe el estatus 501(c)(3)',
  s_bfiTimeline4: 'Recibe subvenciones de SARE',
  s_bfiTimeline5: 'Recibe una subvención de JustFund',
  s_bfiProgram1: 'Directorio en línea gratuito',
  s_bfiProgram2: 'Talleres',
  s_bfiProgram3: 'Eventos en torno a la comida',
  s_bfiProgram4: 'Cajas de regalo seleccionadas',
  s_bfiProgram5: 'Visitas a fincas y reportajes',
  s_bfiProgram6: 'Recopilación de datos e informes',
  s_bfiFounder: 'Dra. Kaia Niambi Shivers, presidenta y fundadora',
  s_bfiContactGeneral: 'Consultas generales',
  s_bfiContactCollab: 'Colaboraciones',
  s_bfiContactDonor: 'Oportunidades para donantes',
  s_bfiContactPress: 'Prensa y medios',
  s_bfiContactPhone: 'Teléfono',
  s_bfiContactMail: 'Correo postal',

  s_checkinMissing: 'Este control no es para tu zona o fue eliminado.',
  s_checkinMetaOpen: 'De BFI · {date} · abierto hasta el {until}',
  s_checkinMetaClosed: 'De BFI · {date} · cerrado',
  s_youAnswered: 'Respondiste: {answer}.',
  s_checkinClosedEmpty: 'Este control ya cerró. Si todavía necesitas ayuda, escríbele a BFI.',
  s_sentCanChange: 'Enviado {when} · puedes cambiarlo abajo',
  s_sentByTextCanChange: 'Enviado {when} por mensaje de texto · puedes cambiarlo abajo',
  s_needPlaceholder: 'Por ejemplo: una motosierra para despejar el camino, un generador para la cámara fría, ayuda para mover animales',
  s_needPrivacy: 'El personal de BFI verá tu nombre, esta nota y el número de teléfono de tus ajustes para poder llamarte.',
  s_checkinResults: 'Resultados (solo personal de BFI)',
  s_statNeedHelp: 'necesitan ayuda',
  s_statOk: 'están bien',
  s_statNoAnswer: 'no han respondido',
  s_byTextShort: 'por texto',
  s_noDetails: 'Sin detalles.',
  s_call: 'Llamar',
  s_text: 'Texto',
  s_noPhone: 'No hay número de teléfono registrado. Escríbele en la app.',
  s_noOneNeedsHelp: 'Nadie ha pedido ayuda todavía.',

  s_checkinsStaffOnly: 'Solo el personal de BFI puede ver los resultados de los controles.',
  s_noCheckins: 'Aún no hay controles. Envía uno después de una tormenta, inundación, incendio o helada fuerte.',
  s_audienceSentOn: '{audience} · enviado el {date}',

  s_broadcastStaffOnly: 'Solo el personal de BFI puede enviar anuncios.',
  s_chPush: 'Notificación',
  s_chEmail: 'Correo electrónico',
  s_chSms: 'Mensaje de texto',
  s_chPushInline: 'notificación',
  s_chEmailInline: 'correo electrónico',
  s_chSmsInline: 'mensaje de texto',
  s_broadcastGoing: 'Tu anuncio se está enviando a {audience}.',
  s_broadcastIntro: 'Los anuncios aparecen en Mensajes → De BFI y se envían por los canales que elijas. Los miembros pueden desactivar cada canal.',
  s_broadcastTitlePlaceholder: 'Entradas para la Collard Green Gala',
  s_broadcastBodyPlaceholder: 'Que sea breve. Los textos se cortan a unos 280 caracteres.',
  s_linkOptional: 'Enlace (opcional)',
  s_linkLabel: 'Texto del enlace',
  s_linkLabelPlaceholder: 'Comprar entradas',
  s_linkHttps: 'Los enlaces deben empezar con https://',
  s_howSent: 'Cómo se envía',
  s_smsCost: 'Cada mensaje de texto cuesta dinero. Úsalos para noticias urgentes o importantes.',
  s_byChannels: 'Por {channels}. No se puede deshacer el envío.',
  s_inboxOnly: 'Solo en la bandeja de la app. No se puede deshacer el envío.',

  s_impactStaffOnly: 'Solo el personal de BFI puede ver el informe de impacto.',
  s_impDirectory: 'Directorio',
  s_impBusiness: 'Negocio para agricultores',
  s_impCommunity: 'Comunidad',
  s_impEvents: 'Eventos y recursos',
  s_imp_farms_live: 'Fincas publicadas en el Index',
  s_imp_farms_verified: 'Verificadas por BFI',
  s_imp_farms_on_app: 'Fincas que se pueden contactar en la app',
  s_imp_farms_pending: 'Esperando revisión',
  s_imp_inquiries_total: 'Consultas enviadas a fincas, en total',
  s_imp_inquiries_30d: 'Consultas, últimos 30 días',
  s_imp_inquiries_answered: 'Consultas aceptadas por los agricultores',
  s_imp_profile_views_30d: 'Visitas a perfiles de fincas, últimos 30 días',
  s_imp_follows: 'Fincas seguidas',
  s_imp_members: 'Miembros',
  s_imp_growers: 'Productores',
  s_imp_messages_30d: 'Mensajes, últimos 30 días',
  s_imp_board_posts_open: 'Publicaciones abiertas en la comunidad',
  s_imp_events_upcoming: 'Próximos eventos',
  s_imp_rsvps: 'Confirmaciones de asistencia',
  s_imp_volunteer_signups: 'Inscripciones de voluntarios',
  s_imp_programs_saved: 'Programas guardados en recordatorios de plazos',
  s_impactReportTitle: 'Informe de impacto de The Index',
  s_impactReportMessage: 'Informe de impacto de The Index, {date}',
  s_couldNotShare: 'No se pudo compartir',
  s_asOf: 'Al {date} · sin datos de muestra',
  s_shareCsv: 'Compartir como CSV',
  s_farmsByRegion: 'Fincas por región',
  s_farmsInRegion: 'Fincas en {region}',
  s_regionFarmsOne: '{region}: 1 finca',
  s_regionFarmsN: '{region}: {n} fincas',

  s_reviewStaffOnly: 'Solo el personal de BFI y los coordinadores regionales pueden ver la cola de revisión.',
  s_newListings: 'Nuevas fincas · {n}',
  s_noListings: 'No hay fincas en espera.',
  s_approveVerify: 'Aprobar y verificar',
  s_decline: 'Rechazar',
  s_approve: 'Aprobar',
  s_eventsCount: 'Eventos · {n}',
  s_noEventsWaiting: 'No hay eventos en espera.',
  s_reportsCount: 'Denuncias · {n}',
  s_noOpenReports: 'No hay denuncias abiertas.',
  s_openListing: 'Abrir ficha',
  s_markResolved: 'Marcar como resuelta',
  s_target_farm: 'Ficha de finca',
  s_target_message: 'Mensaje',
  s_target_event: 'Evento',
  s_target_profile: 'Perfil',
  s_target_post: 'Publicación de la comunidad',

  s_sendCheckinStaffOnly: 'Solo el personal de BFI puede enviar controles.',
  s_checkinIntro:
    'Todos en la zona reciben una notificación y, si lo aceptaron, un mensaje de texto. Responden “Estoy bien” o “Necesito ayuda” con un toque, o contestando SAFE o NEED al texto. Verás quién necesita ayuda, con su número de teléfono, a medida que lleguen las respuestas.',
  s_checkinPlaceholder: 'El huracán Delta pasó anoche por el suroeste de Luisiana. Cuéntennos cómo están ustedes y su finca.',
  s_whichArea: 'Qué zona',
  s_keepOpenFor: 'Mantenerlo abierto',
  s_nDays: '{n} días',
  s_checkinChannels: 'Por notificación y mensaje de texto. Cada texto cuesta dinero. No se puede deshacer el envío.',

  s_surveyMissing: 'Esta encuesta no es para ti o fue eliminada.',
  s_surveyFromBfi: 'Encuesta de BFI',
  s_questionsOne: '1 pregunta',
  s_questionsN: '{n} preguntas',
  s_openUntil: 'abierta hasta el {date}',
  s_draftStaffOnly: 'borrador, solo lo ve el personal',
  s_seeResults: 'Ver resultados',
  s_oneMore: 'Falta una',
  s_pleaseAnswer: 'Responde: {question}',
  s_notRemoved: 'No se eliminó',
  s_thanksAnswers: 'Gracias. Recibimos tus respuestas.',
  s_canChangeUntilClose: 'Puedes cambiarlas hasta que cierre la encuesta.',
  s_surveyClosed: 'Esta encuesta ya cerró.',
  s_howBfiUses: 'Cómo usa BFI tus respuestas',
  s_howBfiUsesBody:
    'El personal de BFI puede ver tus respuestas con tu nombre, para darte seguimiento si pides ayuda. En informes y al defender a los productores, BFI comparte solo totales. Tus respuestas escritas nunca se citan a menos que digas que sí abajo, y aun así sin tu nombre.',
  s_consentQuote: 'BFI puede citar mis respuestas escritas sin mi nombre',
  s_updateAnswers: 'Actualizar mis respuestas',
  s_withdrawAnswers: 'Retirar mis respuestas',
  s_scaleHint: '1 es malo, 5 es excelente',
  s_pickAnyHint: 'Elige todas las que apliquen',

  s_builderStaffOnly: 'Solo el personal de BFI puede crear encuestas.',
  s_needTitle: 'Agrega un título.',
  s_needQuestion: 'Agrega al menos una pregunta.',
  s_needWording: 'Cada pregunta necesita texto.',
  s_needChoices: 'Las preguntas de elegir una o varias necesitan al menos dos opciones.',
  s_builderIntro: 'Los miembros reciben una notificación y un correo cuando se abre la encuesta. Que sea breve: con cinco preguntas o menos se obtienen más respuestas.',
  s_surveyTitlePlaceholder: 'Consulta de la temporada de cultivo 2026',
  s_whyAsking: 'Por qué preguntas (se muestra arriba)',
  s_whyAskingPlaceholder: 'Tus respuestas ayudan a BFI a defender fondos para cámaras frías en la próxima ley agrícola.',
  s_openFor: 'Abierta durante',
  s_weekOne: '1 semana',
  s_weeksN: '{n} semanas',
  s_questions: 'Preguntas',
  s_question: 'Pregunta',
  s_questionN: 'Pregunta {n}',
  s_up: 'Subir',
  s_down: 'Bajar',
  s_remove: 'Quitar',
  s_moveUpA11y: 'Subir la pregunta {n}',
  s_moveDownA11y: 'Bajar la pregunta {n}',
  s_removeA11y: 'Quitar la pregunta {n}',
  s_choicesPerLine: 'Opciones, una por línea',
  s_required: 'Obligatoria',
  s_addQuestion: 'Agregar una pregunta',
  s_goesTo: 'Se envía a {audience} durante {duration}. Las respuestas son privadas para el personal de BFI; las respuestas escritas solo se citan si el miembro lo acepta.',
  s_openSurveyNow: 'Abrir la encuesta ahora',
  s_saveDraft: 'Guardar como borrador',

  s_resultsStaffOnly: 'Solo el personal de BFI puede ver los resultados de las encuestas.',
  s_notChanged: 'No se cambió',
  s_copied: 'Copiado',
  s_copiedBody: 'Los resultados están en tu portapapeles. Pégalos en una hoja de cálculo.',
  s_closesOn: 'cierra el {date}',
  s_responsesOne: '1 respuesta',
  s_responsesN: '{n} respuestas',
  s_mayBeQuoted: '{n} se pueden citar',
  s_openSurvey: 'Abrir encuesta',
  s_closeSurvey: 'Cerrar encuesta',
  s_downloadCsv: 'Descargar CSV',
  s_csvNote: 'El CSV no tiene nombres. Las respuestas escritas de quienes no aceptaron ser citados aparecen como “(not shared)”.',
  s_answeredOf: '{n} de {total} respondieron',
  s_averageOf: 'promedio {avg} de 5',
  s_withheldOne: '1 respuesta escrita más no se muestra: esa persona no aceptó ser citada.',
  s_withheldN: '{n} respuestas escritas más no se muestran: esas personas no aceptaron ser citadas.',

  s_surveysIntro: 'BFI hace algunas preguntas a los miembros de vez en cuando. Los totales les ayudan a defender a los productores negros ante financiadores y legisladores.',
  s_writeSurvey: 'Crear una encuesta',
  s_noSurveys: 'No hay encuestas por ahora.',
  s_answered: 'Respondida',
  s_untilDate: 'hasta el {date}',
};

const fr: Keys = {
  s_open: 'Ouvert',
  s_closed: 'Fermé',
  s_openAction: 'Ouvrir',
  s_surveyOpenPill: 'Ouvert',
  s_surveyClosedPill: 'Fermé',
  s_draft: 'Brouillon',
  s_refresh: 'Actualiser',
  s_notSent: 'Non envoyé',
  s_notSaved: 'Non enregistré',
  s_sent: 'Envoyé',
  s_title: 'Titre',
  s_message: 'Message',
  s_messageOptional: 'Message (facultatif)',
  s_reviewAndSend: 'Vérifier et envoyer',
  s_sendNow: 'Envoyer maintenant',
  s_edit: 'Modifier',
  s_confirmSendTo: 'Envoyer « {title} » ? Destinataires : {audience}.',
  s_results: 'Résultats',

  s_errGeneric: 'Un problème est survenu. Réessayez dans un instant.',
  s_errNotFound: 'Introuvable. L’élément a peut-être été supprimé ou n’est plus public.',
  s_errOffline: 'Vous êtes hors ligne ou la connexion a été coupée. Réessayez quand vous aurez du réseau.',
  s_errFileType: 'Ce type de fichier ne peut pas être envoyé ici. Utilisez une photo (JPEG, PNG, WebP ou HEIC).',
  s_errTooBig: 'Ce fichier est trop lourd. Essayez une photo plus petite ou un enregistrement plus court.',
  s_errNoAccess: 'Vous n’avez pas accès à cette action. Essayez de vous reconnecter.',
  s_errServer: 'Un problème est survenu de notre côté. Réessayez dans un instant.',

  s_updatedToday: 'Mis à jour aujourd’hui',
  s_updatedYesterday: 'Mis à jour hier',
  s_updatedDaysAgo: 'Mis à jour il y a {n} jours',
  s_updatedOn: 'Mis à jour le {date}',

  s_locOff: 'La localisation est désactivée pour The Index. Vous pouvez quand même chercher par région.',
  s_locFailed: 'Impossible de trouver votre position.',
  s_geoNotFound: 'Impossible de trouver « {place} ». Essayez une ville et un État, ou un code postal.',
  s_geoUnavailable: 'La recherche de lieux par nom n’est pas disponible sur cet appareil. Utilisez plutôt votre position.',

  s_pushWeb: 'Les notifications fonctionnent dans les applis iPhone et Android.',
  s_pushSimulator: 'Les notifications nécessitent un vrai téléphone, pas un simulateur.',
  s_pushExpoGo: 'Les notifications nécessitent l’appli installée. Elles ne sont pas disponibles dans Expo Go sur Android.',
  s_pushOff: 'Les notifications de The Index sont désactivées dans les réglages de votre téléphone.',
  s_pushNoProject: 'Il manque l’identifiant de projet EAS dans cette version. Voir docs/NOTIFICATIONS.md.',
  s_pushUnreachable: 'Impossible de joindre le service de notifications. Réessayez plus tard.',

  s_kindNeed: 'Besoin d’aide',
  s_kindNeedHint: 'Bras pour la récolte, transport au marché, conseils',
  s_kindOffer: 'Je propose',
  s_kindOfferHint: 'Plants, surplus de récolte, un savoir-faire',
  s_kindEquipment: 'Matériel',
  s_kindEquipmentHint: 'Outils, tracteurs ou chambre froide à prêter ou partager',
  s_kindRide: 'Trajets et transport',
  s_kindRideHint: 'Covoiturage vers les événements, camions partagés',
  s_kindBulk: 'Achats groupés',
  s_kindBulkHint: 'Regrouper les commandes de semences, d’aliments ou d’emballages',
  s_kindMentor: 'Mentorat',
  s_kindMentorHint: 'Proposer ou demander des conseils à un autre producteur',

  s_qtSingle: 'Un seul choix',
  s_qtMulti: 'Choix multiples',
  s_qtScale: 'De 1 à 5',
  s_qtText: 'Réponse écrite',

  s_bfiTagline: 'Le plus grand annuaire gratuit d’agriculteurs noirs',
  s_bfiStatus: 'Association à but non lucratif 501(c)(3) · Lafayette, LA',
  s_bfiStatGrowers: 'producteurs répertoriés',
  s_bfiStatWomen: 'fermes tenues par des femmes',
  s_bfiStatOrganic: 'bio, naturelles ou régénératrices',
  s_bfiPillar1: 'Renforcer le marketing vers l’écosystème agricole noir',
  s_bfiPillar2: 'Recueillir et partager des informations fiables sur les producteurs noirs',
  s_bfiPillar3: 'Fournir des ressources pour accéder au capital',
  s_bfiPillar4: 'Défendre l’accès aux terres agricoles',
  s_bfiTimeline1: 'Première liste d’agriculteurs noirs publiée comme projet de journalisme de solutions sur Ark Republic',
  s_bfiTimeline2: 'Création de l’association à but non lucratif',
  s_bfiTimeline3: 'Obtention du statut 501(c)(3)',
  s_bfiTimeline4: 'Subventions SARE obtenues',
  s_bfiTimeline5: 'Subvention JustFund obtenue',
  s_bfiProgram1: 'Annuaire en ligne gratuit',
  s_bfiProgram2: 'Ateliers',
  s_bfiProgram3: 'Événements autour de l’alimentation',
  s_bfiProgram4: 'Coffrets cadeaux sélectionnés',
  s_bfiProgram5: 'Visites de fermes et portraits',
  s_bfiProgram6: 'Collecte de données et rapports',
  s_bfiFounder: 'Dr Kaia Niambi Shivers, présidente et fondatrice',
  s_bfiContactGeneral: 'Demandes générales',
  s_bfiContactCollab: 'Collaborations',
  s_bfiContactDonor: 'Dons et mécénat',
  s_bfiContactPress: 'Presse et médias',
  s_bfiContactPhone: 'Téléphone',
  s_bfiContactMail: 'Courrier',

  s_checkinMissing: 'Ce point de contact ne concerne pas votre zone ou a été supprimé.',
  s_checkinMetaOpen: 'De BFI · {date} · ouvert jusqu’au {until}',
  s_checkinMetaClosed: 'De BFI · {date} · fermé',
  s_youAnswered: 'Votre réponse : {answer}.',
  s_checkinClosedEmpty: 'Ce point de contact est fermé. Si vous avez encore besoin d’aide, écrivez à BFI.',
  s_sentCanChange: 'Envoyé {when} · vous pouvez le modifier ci-dessous',
  s_sentByTextCanChange: 'Envoyé {when} par SMS · vous pouvez le modifier ci-dessous',
  s_needPlaceholder: 'Par exemple : une tronçonneuse pour dégager la route, un groupe électrogène pour la chambre froide, de l’aide pour déplacer les animaux',
  s_needPrivacy: 'L’équipe de BFI verra votre nom, cette note et le numéro de téléphone de vos réglages pour pouvoir vous appeler.',
  s_checkinResults: 'Résultats (équipe BFI uniquement)',
  s_statNeedHelp: 'ont besoin d’aide',
  s_statOk: 'vont bien',
  s_statNoAnswer: 'n’ont pas répondu',
  s_byTextShort: 'par SMS',
  s_noDetails: 'Aucun détail.',
  s_call: 'Appeler',
  s_text: 'SMS',
  s_noPhone: 'Aucun numéro enregistré. Écrivez-lui dans l’appli.',
  s_noOneNeedsHelp: 'Personne n’a encore demandé d’aide.',

  s_checkinsStaffOnly: 'Seule l’équipe de BFI peut voir les résultats des points de contact.',
  s_noCheckins: 'Aucun point de contact pour l’instant. Envoyez-en un après une tempête, une inondation, un incendie ou un gel.',
  s_audienceSentOn: '{audience} · envoyé le {date}',

  s_broadcastStaffOnly: 'Seule l’équipe de BFI peut envoyer des annonces.',
  s_chPush: 'Notification',
  s_chEmail: 'E-mail',
  s_chSms: 'SMS',
  s_chPushInline: 'notification',
  s_chEmailInline: 'e-mail',
  s_chSmsInline: 'SMS',
  s_broadcastGoing: 'Votre annonce est en cours d’envoi. Destinataires : {audience}.',
  s_broadcastIntro: 'Les annonces apparaissent dans Messages → De BFI et partent par les canaux choisis. Les membres peuvent désactiver chaque canal.',
  s_broadcastTitlePlaceholder: 'Billets pour le Collard Green Gala',
  s_broadcastBodyPlaceholder: 'Faites court. Les SMS sont coupés vers 280 caractères.',
  s_linkOptional: 'Lien (facultatif)',
  s_linkLabel: 'Texte du lien',
  s_linkLabelPlaceholder: 'Acheter des billets',
  s_linkHttps: 'Les liens doivent commencer par https://',
  s_howSent: 'Mode d’envoi',
  s_smsCost: 'Chaque SMS est payant. Réservez-les aux nouvelles urgentes ou importantes.',
  s_byChannels: 'Par {channels}. L’envoi ne peut pas être annulé.',
  s_inboxOnly: 'Dans la boîte de réception de l’appli seulement. L’envoi ne peut pas être annulé.',

  s_impactStaffOnly: 'Seule l’équipe de BFI peut voir le rapport d’impact.',
  s_impDirectory: 'Annuaire',
  s_impBusiness: 'Activité pour les agriculteurs',
  s_impCommunity: 'Communauté',
  s_impEvents: 'Événements et ressources',
  s_imp_farms_live: 'Fermes en ligne sur l’Index',
  s_imp_farms_verified: 'Vérifiées par BFI',
  s_imp_farms_on_app: 'Fermes joignables dans l’appli',
  s_imp_farms_pending: 'En attente de vérification',
  s_imp_inquiries_total: 'Demandes envoyées aux fermes, au total',
  s_imp_inquiries_30d: 'Demandes, 30 derniers jours',
  s_imp_inquiries_answered: 'Demandes acceptées par les agriculteurs',
  s_imp_profile_views_30d: 'Vues des fiches de fermes, 30 derniers jours',
  s_imp_follows: 'Fermes suivies',
  s_imp_members: 'Membres',
  s_imp_growers: 'Producteurs',
  s_imp_messages_30d: 'Messages, 30 derniers jours',
  s_imp_board_posts_open: 'Annonces ouvertes de la communauté',
  s_imp_events_upcoming: 'Événements à venir',
  s_imp_rsvps: 'Inscriptions',
  s_imp_volunteer_signups: 'Inscriptions de bénévoles',
  s_imp_programs_saved: 'Programmes ajoutés aux rappels d’échéances',
  s_impactReportTitle: 'Rapport d’impact de The Index',
  s_impactReportMessage: 'Rapport d’impact de The Index, {date}',
  s_couldNotShare: 'Partage impossible',
  s_asOf: 'Au {date} · hors données d’exemple',
  s_shareCsv: 'Partager en CSV',
  s_farmsByRegion: 'Fermes par région',
  s_farmsInRegion: 'Fermes – {region}',
  s_regionFarmsOne: '{region} : 1 ferme',
  s_regionFarmsN: '{region} : {n} fermes',

  s_reviewStaffOnly: 'Seuls l’équipe de BFI et les coordinateurs régionaux peuvent voir la file de vérification.',
  s_newListings: 'Nouvelles fiches de fermes · {n}',
  s_noListings: 'Aucune fiche en attente.',
  s_approveVerify: 'Approuver et vérifier',
  s_decline: 'Refuser',
  s_approve: 'Approuver',
  s_eventsCount: 'Événements · {n}',
  s_noEventsWaiting: 'Aucun événement en attente.',
  s_reportsCount: 'Signalements · {n}',
  s_noOpenReports: 'Aucun signalement ouvert.',
  s_openListing: 'Ouvrir la fiche',
  s_markResolved: 'Marquer comme traité',
  s_target_farm: 'Fiche de ferme',
  s_target_message: 'Message',
  s_target_event: 'Événement',
  s_target_profile: 'Profil',
  s_target_post: 'Annonce de la communauté',

  s_sendCheckinStaffOnly: 'Seule l’équipe de BFI peut envoyer des points de contact.',
  s_checkinIntro:
    'Tout le monde dans la zone reçoit une notification et, s’il l’a accepté, un SMS. Chacun répond « Je vais bien » ou « J’ai besoin d’aide » en un geste, ou en répondant SAFE ou NEED au SMS. Vous verrez qui a besoin d’aide, avec son numéro, au fur et à mesure des réponses.',
  s_checkinPlaceholder: 'L’ouragan Delta a traversé le sud-ouest de la Louisiane la nuit dernière. Dites-nous comment vous et votre ferme allez.',
  s_whichArea: 'Quelle zone',
  s_keepOpenFor: 'Laisser ouvert pendant',
  s_nDays: '{n} jours',
  s_checkinChannels: 'Par notification et SMS. Chaque SMS est payant. L’envoi ne peut pas être annulé.',

  s_surveyMissing: 'Ce sondage ne vous concerne pas ou a été supprimé.',
  s_surveyFromBfi: 'Sondage de BFI',
  s_questionsOne: '1 question',
  s_questionsN: '{n} questions',
  s_openUntil: 'ouvert jusqu’au {date}',
  s_draftStaffOnly: 'brouillon, visible par l’équipe seulement',
  s_seeResults: 'Voir les résultats',
  s_oneMore: 'Encore une',
  s_pleaseAnswer: 'Merci de répondre : {question}',
  s_notRemoved: 'Non supprimé',
  s_thanksAnswers: 'Merci. Vos réponses sont enregistrées.',
  s_canChangeUntilClose: 'Vous pouvez les modifier jusqu’à la fermeture du sondage.',
  s_surveyClosed: 'Ce sondage est fermé.',
  s_howBfiUses: 'Comment BFI utilise vos réponses',
  s_howBfiUsesBody:
    'L’équipe de BFI voit vos réponses avec votre nom, pour pouvoir vous recontacter si vous demandez de l’aide. Dans ses rapports et quand elle défend les producteurs, BFI ne partage que des totaux. Vos réponses écrites ne sont jamais citées sans votre accord ci-dessous, et même alors, sans votre nom.',
  s_consentQuote: 'BFI peut citer mes réponses écrites sans mon nom',
  s_updateAnswers: 'Mettre à jour mes réponses',
  s_withdrawAnswers: 'Retirer mes réponses',
  s_scaleHint: '1 = mauvais, 5 = excellent',
  s_pickAnyHint: 'Choisissez toutes les réponses qui s’appliquent',

  s_builderStaffOnly: 'Seule l’équipe de BFI peut rédiger des sondages.',
  s_needTitle: 'Ajoutez un titre.',
  s_needQuestion: 'Ajoutez au moins une question.',
  s_needWording: 'Chaque question doit être rédigée.',
  s_needChoices: 'Les questions à choix unique ou multiple doivent avoir au moins deux choix.',
  s_builderIntro: 'Les membres reçoivent une notification et un e-mail à l’ouverture du sondage. Faites court : cinq questions ou moins obtiennent le plus de réponses.',
  s_surveyTitlePlaceholder: 'Bilan de la saison 2026',
  s_whyAsking: 'Pourquoi vous posez ces questions (affiché en haut)',
  s_whyAskingPlaceholder: 'Vos réponses aident BFI à plaider pour le financement des chambres froides dans la prochaine loi agricole.',
  s_openFor: 'Ouvert pendant',
  s_weekOne: '1 semaine',
  s_weeksN: '{n} semaines',
  s_questions: 'Questions',
  s_question: 'Question',
  s_questionN: 'Question {n}',
  s_up: 'Monter',
  s_down: 'Descendre',
  s_remove: 'Supprimer',
  s_moveUpA11y: 'Monter la question {n}',
  s_moveDownA11y: 'Descendre la question {n}',
  s_removeA11y: 'Supprimer la question {n}',
  s_choicesPerLine: 'Choix, un par ligne',
  s_required: 'Obligatoire',
  s_addQuestion: 'Ajouter une question',
  s_goesTo: 'Destinataires : {audience}, pendant {duration}. Les réponses restent privées pour l’équipe de BFI ; les réponses écrites ne sont citées qu’avec l’accord du membre.',
  s_openSurveyNow: 'Ouvrir le sondage maintenant',
  s_saveDraft: 'Enregistrer comme brouillon',

  s_resultsStaffOnly: 'Seule l’équipe de BFI peut voir les résultats des sondages.',
  s_notChanged: 'Non modifié',
  s_copied: 'Copié',
  s_copiedBody: 'Les résultats sont dans le presse-papiers. Collez-les dans un tableur.',
  s_closesOn: 'ferme le {date}',
  s_responsesOne: '1 réponse',
  s_responsesN: '{n} réponses',
  s_mayBeQuoted: '{n} citables',
  s_openSurvey: 'Ouvrir le sondage',
  s_closeSurvey: 'Fermer le sondage',
  s_downloadCsv: 'Télécharger le CSV',
  s_csvNote: 'Le CSV ne contient aucun nom. Les réponses écrites des membres qui n’ont pas accepté d’être cités sont marquées « (not shared) ».',
  s_answeredOf: '{n} sur {total} ont répondu',
  s_averageOf: 'moyenne {avg} sur 5',
  s_withheldOne: '1 autre réponse écrite non affichée : ce membre n’a pas accepté d’être cité.',
  s_withheldN: '{n} autres réponses écrites non affichées : ces membres n’ont pas accepté d’être cités.',

  s_surveysIntro: 'De temps en temps, BFI pose quelques questions aux membres. Les totaux l’aident à défendre les producteurs noirs auprès des financeurs et des élus.',
  s_writeSurvey: 'Rédiger un sondage',
  s_noSurveys: 'Aucun sondage pour le moment.',
  s_answered: 'Répondu',
  s_untilDate: 'jusqu’au {date}',
};

const ht: Keys = {
  s_open: 'Louvri',
  s_closed: 'Fèmen',
  s_openAction: 'Louvri',
  s_surveyOpenPill: 'Louvri',
  s_surveyClosedPill: 'Fèmen',
  s_draft: 'Bouyon',
  s_refresh: 'Rafrechi',
  s_notSent: 'Pa voye',
  s_notSaved: 'Pa anrejistre',
  s_sent: 'Voye',
  s_title: 'Tit',
  s_message: 'Mesaj',
  s_messageOptional: 'Mesaj (si ou vle)',
  s_reviewAndSend: 'Revize epi voye',
  s_sendNow: 'Voye kounye a',
  s_edit: 'Modifye',
  s_confirmSendTo: 'Voye “{title}” bay {audience}?',
  s_results: 'Rezilta',

  s_errGeneric: 'Gen yon bagay ki pa mache. Eseye ankò nan yon ti moman.',
  s_errNotFound: 'Nou pa jwenn sa. Petèt yo retire l oswa li pa piblik ankò.',
  s_errOffline: 'Ou pa gen koneksyon oswa koneksyon an koupe. Eseye ankò lè ou gen siyal.',
  s_errFileType: 'Ou pa ka voye kalite fichye sa a isit la. Sèvi ak yon foto (JPEG, PNG, WebP oswa HEIC).',
  s_errTooBig: 'Fichye sa a twò gwo. Eseye yon foto ki pi piti oswa yon anrejistreman ki pi kout.',
  s_errNoAccess: 'Ou pa gen dwa fè sa. Eseye konekte ankò.',
  s_errServer: 'Gen yon bagay ki pa mache bò kote nou. Eseye ankò nan yon ti moman.',

  s_updatedToday: 'Mete ajou jodi a',
  s_updatedYesterday: 'Mete ajou yè',
  s_updatedDaysAgo: 'Mete ajou sa gen {n} jou',
  s_updatedOn: 'Mete ajou {date}',

  s_locOff: 'Lokalizasyon fèmen pou The Index. Ou ka toujou chèche pa rejyon.',
  s_locFailed: 'Nou pa rive jwenn kote ou ye.',
  s_geoNotFound: 'Nou pa jwenn “{place}”. Eseye yon vil ak eta, oswa yon kòd postal.',
  s_geoUnavailable: 'Ou pa ka chèche kote pa non sou aparèy sa a. Sèvi ak lokalizasyon ou pito.',

  s_pushWeb: 'Notifikasyon telefòn mache nan aplikasyon iPhone ak Android yo.',
  s_pushSimulator: 'Notifikasyon bezwen yon vrè telefòn, pa yon similatè.',
  s_pushExpoGo: 'Notifikasyon bezwen aplikasyon an enstale. Yo pa disponib nan Expo Go sou Android.',
  s_pushOff: 'Notifikasyon The Index fèmen nan paramèt telefòn ou.',
  s_pushNoProject: 'Vèsyon sa a pa gen id pwojè EAS li. Gade docs/NOTIFICATIONS.md.',
  s_pushUnreachable: 'Nou pa rive jwenn sèvis notifikasyon an. Eseye ankò pita.',

  s_kindNeed: 'Mwen bezwen èd',
  s_kindNeedHint: 'Moun pou rekòt, woulib pou mache, konsèy',
  s_kindOffer: 'Mwen ofri',
  s_kindOfferHint: 'Plantil, rekòt ki rete, yon konpetans',
  s_kindEquipment: 'Ekipman',
  s_kindEquipmentHint: 'Zouti, traktè oswa chanm frèt pou prete oswa pataje',
  s_kindRide: 'Woulib ak transpò',
  s_kindRideHint: 'Woulib pou ale nan evènman, kamyon pataje',
  s_kindBulk: 'Achte ansanm',
  s_kindBulkHint: 'Mete kòmand ansanm pou semans, manje bèt oswa anbalaj',
  s_kindMentor: 'Mantora',
  s_kindMentorHint: 'Ofri oswa mande konsèy bay yon lòt kiltivatè',

  s_qtSingle: 'Chwazi youn',
  s_qtMulti: 'Chwazi plizyè',
  s_qtScale: '1 rive 5',
  s_qtText: 'Repons ekri',

  s_bfiTagline: 'Pi gwo anyè gratis kiltivatè nwa yo',
  s_bfiStatus: 'Òganizasyon san bi likratif 501(c)(3) · Lafayette, LA',
  s_bfiStatGrowers: 'kiltivatè nan lis la',
  s_bfiStatWomen: 'fèm fanm posede',
  s_bfiStatOrganic: 'òganik, natirèl oswa rejeneratif',
  s_bfiPillar1: 'Fè plis maketing pou ekosistèm agrikòl nwa a',
  s_bfiPillar2: 'Ranmase epi pataje bon enfòmasyon sou kiltivatè nwa yo',
  s_bfiPillar3: 'Bay resous pou jwenn aksè a kapital',
  s_bfiPillar4: 'Defann chemen pou jwenn tè pou fè agrikilti',
  s_bfiTimeline1: 'Premye lis kiltivatè nwa pibliye kòm yon pwojè jounalis solisyon sou Ark Republic',
  s_bfiTimeline2: 'Vin yon òganizasyon san bi likratif',
  s_bfiTimeline3: 'Resevwa estati 501(c)(3)',
  s_bfiTimeline4: 'Resevwa sibvansyon SARE',
  s_bfiTimeline5: 'Resevwa sibvansyon JustFund',
  s_bfiProgram1: 'Anyè gratis sou entènèt',
  s_bfiProgram2: 'Atelye',
  s_bfiProgram3: 'Evènman ki santre sou manje',
  s_bfiProgram4: 'Bwat kado chwazi',
  s_bfiProgram5: 'Vizit fèm ak istwa sou fèm yo',
  s_bfiProgram6: 'Ranmase done ak rapò',
  s_bfiFounder: 'Dr. Kaia Niambi Shivers, prezidan ak fondatris',
  s_bfiContactGeneral: 'Kesyon jeneral',
  s_bfiContactCollab: 'Kolaborasyon',
  s_bfiContactDonor: 'Pou donatè',
  s_bfiContactPress: 'Laprès ak medya',
  s_bfiContactPhone: 'Telefòn',
  s_bfiContactMail: 'Lapòs',

  s_checkinMissing: 'Mesaj pou pran nouvèl sa a pa pou zòn ou, oswa yo retire l.',
  s_checkinMetaOpen: 'Soti nan BFI · {date} · louvri jiska {until}',
  s_checkinMetaClosed: 'Soti nan BFI · {date} · fèmen',
  s_youAnswered: 'Ou reponn: {answer}.',
  s_checkinClosedEmpty: 'Mesaj pou pran nouvèl sa a fèmen. Si ou toujou bezwen èd, ekri BFI.',
  s_sentCanChange: 'Voye {when} · ou ka chanje l anba a',
  s_sentByTextCanChange: 'Voye {when} pa tèks · ou ka chanje l anba a',
  s_needPlaceholder: 'Pa egzanp: yon tronsonnèz pou netwaye wout la, yon dèlko pou frijidè a, èd pou deplase bèt yo',
  s_needPrivacy: 'Ekip BFI a ap wè non ou, nòt sa a ak nimewo telefòn ki nan paramèt ou pou yo ka rele w.',
  s_checkinResults: 'Rezilta (ekip BFI sèlman)',
  s_statNeedHelp: 'bezwen èd',
  s_statOk: 'byen',
  s_statNoAnswer: 'poko reponn',
  s_byTextShort: 'pa tèks',
  s_noDetails: 'Pa gen detay.',
  s_call: 'Rele',
  s_text: 'Tèks',
  s_noPhone: 'Pa gen nimewo telefòn anrejistre. Ekri moun nan nan aplikasyon an.',
  s_noOneNeedsHelp: 'Pèsonn poko mande èd.',

  s_checkinsStaffOnly: 'Se ekip BFI sèlman ki ka wè rezilta mesaj pou pran nouvèl yo.',
  s_noCheckins: 'Poko gen mesaj pou pran nouvèl. Voye youn apre yon tanpèt, inondasyon, dife oswa gwo jèl.',
  s_audienceSentOn: '{audience} · voye {date}',

  s_broadcastStaffOnly: 'Se ekip BFI sèlman ki ka voye anons.',
  s_chPush: 'Notifikasyon telefòn',
  s_chEmail: 'Imèl',
  s_chSms: 'Mesaj tèks',
  s_chPushInline: 'notifikasyon telefòn',
  s_chEmailInline: 'imèl',
  s_chSmsInline: 'mesaj tèks',
  s_broadcastGoing: 'Anons ou an ap pati bay {audience}.',
  s_broadcastIntro: 'Anons yo parèt nan Mesaj → Soti nan BFI epi yo pati sou kanal ou chwazi yo. Manm yo ka fèmen chak kanal.',
  s_broadcastTitlePlaceholder: 'Tikè pou Collard Green Gala',
  s_broadcastBodyPlaceholder: 'Fè l kout. Tèks yo koupe apeprè nan 280 karaktè.',
  s_linkOptional: 'Lyen (si ou vle)',
  s_linkLabel: 'Tèks lyen an',
  s_linkLabelPlaceholder: 'Achte tikè',
  s_linkHttps: 'Lyen yo dwe kòmanse ak https://',
  s_howSent: 'Kijan li voye',
  s_smsCost: 'Chak mesaj tèks koute lajan. Sèvi ak yo pou nouvèl ijan oswa enpòtan.',
  s_byChannels: 'Pa {channels}. Ou pa ka anile l apre.',
  s_inboxOnly: 'Nan bwat mesaj aplikasyon an sèlman. Ou pa ka anile l apre.',

  s_impactStaffOnly: 'Se ekip BFI sèlman ki ka wè rapò enpak la.',
  s_impDirectory: 'Anyè',
  s_impBusiness: 'Biznis pou kiltivatè',
  s_impCommunity: 'Kominote',
  s_impEvents: 'Evènman ak resous',
  s_imp_farms_live: 'Fèm ki parèt sou Index la',
  s_imp_farms_verified: 'Verifye pa BFI',
  s_imp_farms_on_app: 'Fèm ou ka kontakte nan aplikasyon an',
  s_imp_farms_pending: 'Ap tann revizyon',
  s_imp_inquiries_total: 'Demann voye bay fèm, total',
  s_imp_inquiries_30d: 'Demann, 30 dènye jou',
  s_imp_inquiries_answered: 'Demann kiltivatè yo di wi',
  s_imp_profile_views_30d: 'Vizit pwofil fèm, 30 dènye jou',
  s_imp_follows: 'Fèm moun ap swiv',
  s_imp_members: 'Manm',
  s_imp_growers: 'Kiltivatè',
  s_imp_messages_30d: 'Mesaj, 30 dènye jou',
  s_imp_board_posts_open: 'Piblikasyon kominote ki louvri',
  s_imp_events_upcoming: 'Evènman k ap vini',
  s_imp_rsvps: 'Konfimasyon prezans',
  s_imp_volunteer_signups: 'Enskripsyon volontè',
  s_imp_programs_saved: 'Pwogram anrejistre nan rapèl dat limit',
  s_impactReportTitle: 'Rapò enpak The Index',
  s_impactReportMessage: 'Rapò enpak The Index, {date}',
  s_couldNotShare: 'Pa t ka pataje',
  s_asOf: 'Jiska {date} · san done egzanp',
  s_shareCsv: 'Pataje an CSV',
  s_farmsByRegion: 'Fèm pa rejyon',
  s_farmsInRegion: 'Fèm nan {region}',
  s_regionFarmsOne: '{region}: 1 fèm',
  s_regionFarmsN: '{region}: {n} fèm',

  s_reviewStaffOnly: 'Se ekip BFI ak kowòdonatè rejyonal yo sèlman ki ka wè lis revizyon an.',
  s_newListings: 'Nouvo fèm · {n}',
  s_noListings: 'Pa gen fèm k ap tann.',
  s_approveVerify: 'Apwouve epi verifye',
  s_decline: 'Refize',
  s_approve: 'Apwouve',
  s_eventsCount: 'Evènman · {n}',
  s_noEventsWaiting: 'Pa gen evènman k ap tann.',
  s_reportsCount: 'Siyalman · {n}',
  s_noOpenReports: 'Pa gen siyalman ki louvri.',
  s_openListing: 'Louvri fich la',
  s_markResolved: 'Make kòm rezoud',
  s_target_farm: 'Fich fèm',
  s_target_message: 'Mesaj',
  s_target_event: 'Evènman',
  s_target_profile: 'Pwofil',
  s_target_post: 'Piblikasyon kominote',

  s_sendCheckinStaffOnly: 'Se ekip BFI sèlman ki ka voye mesaj pou pran nouvèl.',
  s_checkinIntro:
    'Tout moun nan zòn nan resevwa yon notifikasyon epi, si yo te dakò, yon tèks. Yo reponn “Mwen byen” oswa “Mwen bezwen èd” ak yon sèl tap, oswa lè yo reponn SAFE oswa NEED nan tèks la. W ap wè kiyès ki bezwen èd, ak nimewo telefòn yo, pandan repons yo ap rantre.',
  s_checkinPlaceholder: 'Siklòn Delta te pase nan sidwès Lwizyàn yè swa. Fè nou konnen kijan ou menm ak fèm ou ye.',
  s_whichArea: 'Ki zòn',
  s_keepOpenFor: 'Kite l louvri pandan',
  s_nDays: '{n} jou',
  s_checkinChannels: 'Pa notifikasyon telefòn ak mesaj tèks. Chak tèks koute lajan. Ou pa ka anile l apre.',

  s_surveyMissing: 'Sondaj sa a pa pou ou, oswa yo retire l.',
  s_surveyFromBfi: 'Sondaj BFI',
  s_questionsOne: '1 kesyon',
  s_questionsN: '{n} kesyon',
  s_openUntil: 'louvri jiska {date}',
  s_draftStaffOnly: 'bouyon, se ekip la sèlman ki ka wè l',
  s_seeResults: 'Wè rezilta yo',
  s_oneMore: 'Youn ankò',
  s_pleaseAnswer: 'Tanpri reponn: {question}',
  s_notRemoved: 'Pa retire',
  s_thanksAnswers: 'Mèsi. Nou resevwa repons ou yo.',
  s_canChangeUntilClose: 'Ou ka chanje yo jiskaske sondaj la fèmen.',
  s_surveyClosed: 'Sondaj sa a fèmen.',
  s_howBfiUses: 'Kijan BFI sèvi ak repons ou yo',
  s_howBfiUsesBody:
    'Ekip BFI a ka wè repons ou yo ak non ou, pou yo ka swiv ou si ou mande èd. Nan rapò yo ak lè l ap defann kiltivatè yo, BFI pataje total sèlman. Yo pa janm site repons ekri ou yo si ou pa di wi anba a, e menm lè sa a, san non ou.',
  s_consentQuote: 'BFI ka site repons ekri mwen yo san non mwen',
  s_updateAnswers: 'Mete repons mwen yo ajou',
  s_withdrawAnswers: 'Retire repons mwen yo',
  s_scaleHint: '1 se pa bon, 5 se ekselan',
  s_pickAnyHint: 'Chwazi tout sa ki aplike',

  s_builderStaffOnly: 'Se ekip BFI sèlman ki ka ekri sondaj.',
  s_needTitle: 'Mete yon tit.',
  s_needQuestion: 'Mete omwen yon kesyon.',
  s_needWording: 'Chak kesyon bezwen tèks.',
  s_needChoices: 'Kesyon “chwazi youn” ak “chwazi plizyè” bezwen omwen de chwa.',
  s_builderIntro: 'Manm yo resevwa yon notifikasyon ak yon imèl lè sondaj la louvri. Fè l kout: senk kesyon oswa mwens jwenn plis repons.',
  s_surveyTitlePlaceholder: 'Tcheke sezon plantasyon 2026',
  s_whyAsking: 'Poukisa w ap mande (parèt anwo)',
  s_whyAskingPlaceholder: 'Repons ou yo ede BFI defann lajan pou chanm frèt nan pwochen lwa agrikòl la.',
  s_openFor: 'Louvri pandan',
  s_weekOne: '1 semèn',
  s_weeksN: '{n} semèn',
  s_questions: 'Kesyon',
  s_question: 'Kesyon',
  s_questionN: 'Kesyon {n}',
  s_up: 'Monte',
  s_down: 'Desann',
  s_remove: 'Retire',
  s_moveUpA11y: 'Monte kesyon {n}',
  s_moveDownA11y: 'Desann kesyon {n}',
  s_removeA11y: 'Retire kesyon {n}',
  s_choicesPerLine: 'Chwa, youn pa liy',
  s_required: 'Obligatwa',
  s_addQuestion: 'Ajoute yon kesyon',
  s_goesTo: 'Ale bay {audience} pandan {duration}. Repons yo rete prive pou ekip BFI a; yo site repons ekri sèlman lè manm nan dakò.',
  s_openSurveyNow: 'Louvri sondaj la kounye a',
  s_saveDraft: 'Anrejistre kòm bouyon',

  s_resultsStaffOnly: 'Se ekip BFI sèlman ki ka wè rezilta sondaj yo.',
  s_notChanged: 'Pa chanje',
  s_copied: 'Kopye',
  s_copiedBody: 'Rezilta yo nan presse-papye ou. Kole yo nan yon tablo.',
  s_closesOn: 'ap fèmen {date}',
  s_responsesOne: '1 repons',
  s_responsesN: '{n} repons',
  s_mayBeQuoted: '{n} ka site',
  s_openSurvey: 'Louvri sondaj la',
  s_closeSurvey: 'Fèmen sondaj la',
  s_downloadCsv: 'Telechaje CSV',
  s_csvNote: 'CSV a pa gen non. Repons ekri manm ki pa dakò pou yo site yo make “(not shared)”.',
  s_answeredOf: '{n} sou {total} reponn',
  s_averageOf: 'mwayèn {avg} sou 5',
  s_withheldOne: '1 lòt repons ekri pa parèt: manm sa a pa dakò pou yo site l.',
  s_withheldN: '{n} lòt repons ekri pa parèt: manm sa yo pa dakò pou yo site yo.',

  s_surveysIntro: 'De tanzantan, BFI poze manm yo kèk kesyon. Total yo ede l defann kiltivatè nwa yo devan moun k ap finanse ak lejislatè yo.',
  s_writeSurvey: 'Ekri yon sondaj',
  s_noSurveys: 'Pa gen sondaj kounye a.',
  s_answered: 'Reponn',
  s_untilDate: 'jiska {date}',
};

const pt: Keys = {
  s_open: 'Aberto',
  s_closed: 'Encerrado',
  s_openAction: 'Abrir',
  s_surveyOpenPill: 'Aberta',
  s_surveyClosedPill: 'Encerrada',
  s_draft: 'Rascunho',
  s_refresh: 'Atualizar',
  s_notSent: 'Não enviado',
  s_notSaved: 'Não salvo',
  s_sent: 'Enviado',
  s_title: 'Título',
  s_message: 'Mensagem',
  s_messageOptional: 'Mensagem (opcional)',
  s_reviewAndSend: 'Revisar e enviar',
  s_sendNow: 'Enviar agora',
  s_edit: 'Editar',
  s_confirmSendTo: 'Enviar “{title}” para {audience}?',
  s_results: 'Resultados',

  s_errGeneric: 'Algo deu errado. Tente de novo daqui a pouco.',
  s_errNotFound: 'Não encontramos isso. Pode ter sido removido ou não ser mais público.',
  s_errOffline: 'Você está sem internet ou a conexão caiu. Tente de novo quando tiver sinal.',
  s_errFileType: 'Esse tipo de arquivo não pode ser enviado aqui. Use uma foto (JPEG, PNG, WebP ou HEIC).',
  s_errTooBig: 'Esse arquivo é grande demais. Tente uma foto menor ou uma gravação mais curta.',
  s_errNoAccess: 'Você não tem acesso para fazer isso. Tente entrar de novo.',
  s_errServer: 'Algo deu errado do nosso lado. Tente de novo daqui a pouco.',

  s_updatedToday: 'Atualizado hoje',
  s_updatedYesterday: 'Atualizado ontem',
  s_updatedDaysAgo: 'Atualizado há {n} dias',
  s_updatedOn: 'Atualizado em {date}',

  s_locOff: 'A localização está desativada para o The Index. Você ainda pode buscar por região.',
  s_locFailed: 'Não foi possível encontrar sua localização.',
  s_geoNotFound: 'Não encontramos “{place}”. Tente uma cidade e estado, ou um CEP.',
  s_geoUnavailable: 'A busca de lugares por nome não está disponível neste aparelho. Use sua localização.',

  s_pushWeb: 'As notificações funcionam nos apps de iPhone e Android.',
  s_pushSimulator: 'As notificações precisam de um celular de verdade, não de um simulador.',
  s_pushExpoGo: 'As notificações precisam do app instalado. Elas não funcionam no Expo Go no Android.',
  s_pushOff: 'As notificações do The Index estão desativadas nos ajustes do seu celular.',
  s_pushNoProject: 'Esta versão está sem o id do projeto EAS. Veja docs/NOTIFICATIONS.md.',
  s_pushUnreachable: 'Não foi possível acessar o serviço de notificações. Tente mais tarde.',

  s_kindNeed: 'Preciso de ajuda',
  s_kindNeedHint: 'Mãos na colheita, carona até a feira, conselhos',
  s_kindOffer: 'Ofereço',
  s_kindOfferHint: 'Mudas, sobra de produção, uma habilidade',
  s_kindEquipment: 'Equipamentos',
  s_kindEquipmentHint: 'Ferramentas, tratores ou câmara fria para emprestar ou dividir',
  s_kindRide: 'Caronas e fretes',
  s_kindRideHint: 'Caronas para eventos, caminhão compartilhado',
  s_kindBulk: 'Compras em grupo',
  s_kindBulkHint: 'Juntar pedidos de sementes, ração ou embalagens',
  s_kindMentor: 'Mentoria',
  s_kindMentorHint: 'Ofereça ou peça orientação a outro produtor',

  s_qtSingle: 'Escolher uma',
  s_qtMulti: 'Escolher várias',
  s_qtScale: 'De 1 a 5',
  s_qtText: 'Resposta escrita',

  s_bfiTagline: 'O maior diretório gratuito de agricultores negros',
  s_bfiStatus: 'Organização sem fins lucrativos 501(c)(3) · Lafayette, LA',
  s_bfiStatGrowers: 'produtores cadastrados',
  s_bfiStatWomen: 'fazendas de mulheres',
  s_bfiStatOrganic: 'orgânicas, naturais ou regenerativas',
  s_bfiPillar1: 'Ampliar o marketing voltado ao ecossistema agrícola negro',
  s_bfiPillar2: 'Reunir e compartilhar informações precisas sobre produtores negros',
  s_bfiPillar3: 'Oferecer recursos para acesso a capital',
  s_bfiPillar4: 'Defender caminhos de acesso à terra',
  s_bfiTimeline1: 'Primeira lista de agricultores negros publicada como projeto de jornalismo de soluções na Ark Republic',
  s_bfiTimeline2: 'Fundada como organização sem fins lucrativos',
  s_bfiTimeline3: 'Recebe o status 501(c)(3)',
  s_bfiTimeline4: 'Recebe subsídios do SARE',
  s_bfiTimeline5: 'Recebe subsídio do JustFund',
  s_bfiProgram1: 'Diretório on-line gratuito',
  s_bfiProgram2: 'Oficinas',
  s_bfiProgram3: 'Eventos em torno da comida',
  s_bfiProgram4: 'Caixas de presente selecionadas',
  s_bfiProgram5: 'Visitas a fazendas e reportagens',
  s_bfiProgram6: 'Coleta de dados e relatórios',
  s_bfiFounder: 'Dra. Kaia Niambi Shivers, presidente e fundadora',
  s_bfiContactGeneral: 'Dúvidas gerais',
  s_bfiContactCollab: 'Parcerias',
  s_bfiContactDonor: 'Oportunidades para doadores',
  s_bfiContactPress: 'Imprensa e mídia',
  s_bfiContactPhone: 'Telefone',
  s_bfiContactMail: 'Correio',

  s_checkinMissing: 'Este pedido de notícias não é para a sua região ou foi removido.',
  s_checkinMetaOpen: 'Da BFI · {date} · aberto até {until}',
  s_checkinMetaClosed: 'Da BFI · {date} · encerrado',
  s_youAnswered: 'Sua resposta: {answer}.',
  s_checkinClosedEmpty: 'Este pedido de notícias foi encerrado. Se você ainda precisa de ajuda, mande uma mensagem para a BFI.',
  s_sentCanChange: 'Enviado {when} · você pode mudar abaixo',
  s_sentByTextCanChange: 'Enviado {when} por SMS · você pode mudar abaixo',
  s_needPlaceholder: 'Por exemplo: uma motosserra para liberar a estrada, um gerador para a câmara fria, ajuda para mover os animais',
  s_needPrivacy: 'A equipe da BFI verá seu nome, esta nota e o telefone das suas configurações para poder ligar para você.',
  s_checkinResults: 'Resultados (só equipe da BFI)',
  s_statNeedHelp: 'precisam de ajuda',
  s_statOk: 'estão bem',
  s_statNoAnswer: 'não responderam',
  s_byTextShort: 'por SMS',
  s_noDetails: 'Sem detalhes.',
  s_call: 'Ligar',
  s_text: 'SMS',
  s_noPhone: 'Nenhum telefone cadastrado. Mande uma mensagem pelo app.',
  s_noOneNeedsHelp: 'Ninguém pediu ajuda ainda.',

  s_checkinsStaffOnly: 'Só a equipe da BFI pode ver os resultados dos pedidos de notícias.',
  s_noCheckins: 'Nenhum pedido de notícias ainda. Envie um depois de uma tempestade, enchente, incêndio ou geada forte.',
  s_audienceSentOn: '{audience} · enviado em {date}',

  s_broadcastStaffOnly: 'Só a equipe da BFI pode enviar avisos.',
  s_chPush: 'Notificação',
  s_chEmail: 'E-mail',
  s_chSms: 'SMS',
  s_chPushInline: 'notificação',
  s_chEmailInline: 'e-mail',
  s_chSmsInline: 'SMS',
  s_broadcastGoing: 'Seu aviso está sendo enviado para {audience}.',
  s_broadcastIntro: 'Os avisos aparecem em Mensagens → Da BFI e saem pelos canais que você escolher. Os membros podem desativar cada canal.',
  s_broadcastTitlePlaceholder: 'Ingressos para o Collard Green Gala',
  s_broadcastBodyPlaceholder: 'Seja breve. Os SMS são cortados em cerca de 280 caracteres.',
  s_linkOptional: 'Link (opcional)',
  s_linkLabel: 'Texto do link',
  s_linkLabelPlaceholder: 'Comprar ingressos',
  s_linkHttps: 'Os links precisam começar com https://',
  s_howSent: 'Como é enviado',
  s_smsCost: 'Cada SMS custa dinheiro. Use para notícias urgentes ou importantes.',
  s_byChannels: 'Por {channels}. Não dá para desfazer o envio.',
  s_inboxOnly: 'Só na caixa de entrada do app. Não dá para desfazer o envio.',

  s_impactStaffOnly: 'Só a equipe da BFI pode ver o relatório de impacto.',
  s_impDirectory: 'Diretório',
  s_impBusiness: 'Negócios para agricultores',
  s_impCommunity: 'Comunidade',
  s_impEvents: 'Eventos e recursos',
  s_imp_farms_live: 'Fazendas publicadas no Index',
  s_imp_farms_verified: 'Verificadas pela BFI',
  s_imp_farms_on_app: 'Fazendas que recebem mensagens no app',
  s_imp_farms_pending: 'Aguardando revisão',
  s_imp_inquiries_total: 'Pedidos enviados às fazendas, total',
  s_imp_inquiries_30d: 'Pedidos, últimos 30 dias',
  s_imp_inquiries_answered: 'Pedidos aceitos pelos agricultores',
  s_imp_profile_views_30d: 'Visitas a perfis de fazendas, últimos 30 dias',
  s_imp_follows: 'Fazendas seguidas',
  s_imp_members: 'Membros',
  s_imp_growers: 'Produtores',
  s_imp_messages_30d: 'Mensagens, últimos 30 dias',
  s_imp_board_posts_open: 'Publicações abertas na comunidade',
  s_imp_events_upcoming: 'Próximos eventos',
  s_imp_rsvps: 'Presenças confirmadas',
  s_imp_volunteer_signups: 'Inscrições de voluntários',
  s_imp_programs_saved: 'Programas salvos nos lembretes de prazos',
  s_impactReportTitle: 'Relatório de impacto do The Index',
  s_impactReportMessage: 'Relatório de impacto do The Index, {date}',
  s_couldNotShare: 'Não foi possível compartilhar',
  s_asOf: 'Em {date} · sem dados de exemplo',
  s_shareCsv: 'Compartilhar como CSV',
  s_farmsByRegion: 'Fazendas por região',
  s_farmsInRegion: 'Fazendas em {region}',
  s_regionFarmsOne: '{region}: 1 fazenda',
  s_regionFarmsN: '{region}: {n} fazendas',

  s_reviewStaffOnly: 'Só a equipe da BFI e os coordenadores regionais podem ver a fila de revisão.',
  s_newListings: 'Novos cadastros de fazendas · {n}',
  s_noListings: 'Nenhum cadastro aguardando.',
  s_approveVerify: 'Aprovar e verificar',
  s_decline: 'Recusar',
  s_approve: 'Aprovar',
  s_eventsCount: 'Eventos · {n}',
  s_noEventsWaiting: 'Nenhum evento aguardando.',
  s_reportsCount: 'Denúncias · {n}',
  s_noOpenReports: 'Nenhuma denúncia aberta.',
  s_openListing: 'Abrir cadastro',
  s_markResolved: 'Marcar como resolvida',
  s_target_farm: 'Cadastro de fazenda',
  s_target_message: 'Mensagem',
  s_target_event: 'Evento',
  s_target_profile: 'Perfil',
  s_target_post: 'Publicação da comunidade',

  s_sendCheckinStaffOnly: 'Só a equipe da BFI pode enviar pedidos de notícias.',
  s_checkinIntro:
    'Todos na região recebem uma notificação e, se tiverem aceitado, um SMS. Eles respondem “Estou bem” ou “Preciso de ajuda” com um toque, ou respondendo SAFE ou NEED ao SMS. Você verá quem precisa de ajuda, com o telefone, conforme as respostas chegam.',
  s_checkinPlaceholder: 'O furacão Delta passou pelo sudoeste da Louisiana ontem à noite. Conte para a gente como você e sua fazenda estão.',
  s_whichArea: 'Qual região',
  s_keepOpenFor: 'Deixar aberto por',
  s_nDays: '{n} dias',
  s_checkinChannels: 'Por notificação e SMS. Cada SMS custa dinheiro. Não dá para desfazer o envio.',

  s_surveyMissing: 'Esta pesquisa não é para você ou foi removida.',
  s_surveyFromBfi: 'Pesquisa da BFI',
  s_questionsOne: '1 pergunta',
  s_questionsN: '{n} perguntas',
  s_openUntil: 'aberta até {date}',
  s_draftStaffOnly: 'rascunho, só a equipe vê',
  s_seeResults: 'Ver resultados',
  s_oneMore: 'Falta uma',
  s_pleaseAnswer: 'Responda: {question}',
  s_notRemoved: 'Não removido',
  s_thanksAnswers: 'Obrigado. Recebemos suas respostas.',
  s_canChangeUntilClose: 'Você pode mudá-las até a pesquisa encerrar.',
  s_surveyClosed: 'Esta pesquisa foi encerrada.',
  s_howBfiUses: 'Como a BFI usa suas respostas',
  s_howBfiUsesBody:
    'A equipe da BFI vê suas respostas com seu nome, para poder entrar em contato se você pedir ajuda. Em relatórios e ao defender os produtores, a BFI só compartilha totais. Suas respostas escritas nunca são citadas sem o seu sim abaixo, e mesmo assim sem o seu nome.',
  s_consentQuote: 'A BFI pode citar minhas respostas escritas sem meu nome',
  s_updateAnswers: 'Atualizar minhas respostas',
  s_withdrawAnswers: 'Retirar minhas respostas',
  s_scaleHint: '1 é ruim, 5 é excelente',
  s_pickAnyHint: 'Escolha todas as que se aplicam',

  s_builderStaffOnly: 'Só a equipe da BFI pode criar pesquisas.',
  s_needTitle: 'Adicione um título.',
  s_needQuestion: 'Adicione pelo menos uma pergunta.',
  s_needWording: 'Toda pergunta precisa de texto.',
  s_needChoices: 'Perguntas de escolher uma ou várias precisam de pelo menos duas opções.',
  s_builderIntro: 'Os membros recebem uma notificação e um e-mail quando a pesquisa abre. Seja breve: com cinco perguntas ou menos vêm mais respostas.',
  s_surveyTitlePlaceholder: 'Balanço da safra 2026',
  s_whyAsking: 'Por que você está perguntando (aparece no topo)',
  s_whyAskingPlaceholder: 'Suas respostas ajudam a BFI a defender recursos para câmaras frias na próxima lei agrícola.',
  s_openFor: 'Aberta por',
  s_weekOne: '1 semana',
  s_weeksN: '{n} semanas',
  s_questions: 'Perguntas',
  s_question: 'Pergunta',
  s_questionN: 'Pergunta {n}',
  s_up: 'Subir',
  s_down: 'Descer',
  s_remove: 'Remover',
  s_moveUpA11y: 'Subir a pergunta {n}',
  s_moveDownA11y: 'Descer a pergunta {n}',
  s_removeA11y: 'Remover a pergunta {n}',
  s_choicesPerLine: 'Opções, uma por linha',
  s_required: 'Obrigatória',
  s_addQuestion: 'Adicionar uma pergunta',
  s_goesTo: 'Vai para {audience} por {duration}. As respostas ficam restritas à equipe da BFI; respostas escritas só são citadas quando o membro concorda.',
  s_openSurveyNow: 'Abrir a pesquisa agora',
  s_saveDraft: 'Salvar como rascunho',

  s_resultsStaffOnly: 'Só a equipe da BFI pode ver os resultados das pesquisas.',
  s_notChanged: 'Não alterado',
  s_copied: 'Copiado',
  s_copiedBody: 'Os resultados estão na área de transferência. Cole em uma planilha.',
  s_closesOn: 'encerra em {date}',
  s_responsesOne: '1 resposta',
  s_responsesN: '{n} respostas',
  s_mayBeQuoted: '{n} podem ser citadas',
  s_openSurvey: 'Abrir pesquisa',
  s_closeSurvey: 'Encerrar pesquisa',
  s_downloadCsv: 'Baixar CSV',
  s_csvNote: 'O CSV não tem nomes. Respostas escritas de membros que não aceitaram ser citados aparecem como “(not shared)”.',
  s_answeredOf: '{n} de {total} responderam',
  s_averageOf: 'média {avg} de 5',
  s_withheldOne: 'Mais 1 resposta escrita não exibida: esse membro não aceitou ser citado.',
  s_withheldN: 'Mais {n} respostas escritas não exibidas: esses membros não aceitaram ser citados.',

  s_surveysIntro: 'De vez em quando, a BFI faz algumas perguntas aos membros. Os totais ajudam a defender os produtores negros junto a financiadores e legisladores.',
  s_writeSurvey: 'Criar uma pesquisa',
  s_noSurveys: 'Nenhuma pesquisa no momento.',
  s_answered: 'Respondida',
  s_untilDate: 'até {date}',
};

export default { en, es, fr, ht, pt };
